/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantszzbOdRnWpv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _ZZBOd-rnWpv/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantszzbOdRnWpv
});
