/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: rKjxpBEYMqtw

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import Checkbox from "../../Checkbox"; // plasmic-import: N2yXmzTT7-_P/component
import SignInWithGoogle from "../../SignInWithGoogle"; // plasmic-import: 1hBCXOAhDfpm/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicLCCreateAccount.module.css"; // plasmic-import: rKjxpBEYMqtw/css

import UserSvgIcon from "./icons/PlasmicIcon__UserSvg"; // plasmic-import: -m2qayguHrPf/icon
import LockSvgIcon from "./icons/PlasmicIcon__LockSvg"; // plasmic-import: qjaD0kAu4SMs/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon

createPlasmicElementProxy;

export type PlasmicLCCreateAccount__VariantMembers = {};
export type PlasmicLCCreateAccount__VariantsArgs = {};
type VariantPropType = keyof PlasmicLCCreateAccount__VariantsArgs;
export const PlasmicLCCreateAccount__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLCCreateAccount__ArgsType = {};
type ArgPropType = keyof PlasmicLCCreateAccount__ArgsType;
export const PlasmicLCCreateAccount__ArgProps = new Array<ArgPropType>();

export type PlasmicLCCreateAccount__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  rectangle?: Flex__<"div">;
  h6?: Flex__<"h6">;
  form2?: Flex__<typeof FormWrapper>;
  input2?: Flex__<typeof AntdInput>;
  input3?: Flex__<typeof AntdInput>;
  input4?: Flex__<typeof AntdInput>;
  errorText?: Flex__<"div">;
  loginButton?: Flex__<typeof LoginButton>;
  checkbox2?: Flex__<typeof Checkbox>;
  freeBox?: Flex__<"div">;
  signInWithGoogle?: Flex__<typeof SignInWithGoogle>;
  createAccount?: Flex__<"div">;
};

export interface DefaultLCCreateAccountProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLCCreateAccount__RenderFunc(props: {
  variants: PlasmicLCCreateAccount__VariantsArgs;
  args: PlasmicLCCreateAccount__ArgsType;
  overrides: PlasmicLCCreateAccount__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form2.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form2",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form2.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form2",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input4.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "checkbox2.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicLCCreateAccount.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicLCCreateAccount.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicLCCreateAccount.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"auto"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "400px"
                : "700px"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
              fullWidth: 297,
              fullHeight: 210,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"rectangle"}
            data-plasmic-override={overrides.rectangle}
            className={classNames(projectcss.all, sty.rectangle)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oCjRw
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h6
                    data-plasmic-name={"h6"}
                    data-plasmic-override={overrides.h6}
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6
                    )}
                  >
                    {"Create corporative account"}
                  </h6>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            {(() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.form2),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["form2", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelAlign: "left",
                labelCol: (() => {
                  const __composite = { span: null, horizontalOnly: true };
                  __composite["span"] = 2;
                  return __composite;
                })(),

                layout: "horizontal",
                mode: "advanced",
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["form2", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["form2"] = ref;
                },
                submitSlot: null,
                wrapperCol: (() => {
                  const __composite = { span: null, horizontalOnly: true };
                  __composite["span"] = 22;
                  return __composite;
                })()
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "form2.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "form2.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"form2"}
                  data-plasmic-override={overrides.form2}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__bwLhI
                    )}
                    label={
                      <UserSvgIcon
                        className={classNames(projectcss.all, sty.svg__f2O7)}
                        role={"img"}
                      />
                    }
                    name={"email"}
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input2),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input2", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        placeholder: "email",
                        size: "middle",
                        type: "email",
                        value: generateStateValueProp($state, [
                          "input2",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input2.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input2"}
                          data-plasmic-override={overrides.input2}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___4XlWd
                    )}
                    label={
                      <LockSvgIcon
                        className={classNames(projectcss.all, sty.svg__elYWb)}
                        role={"img"}
                      />
                    }
                    name={"password"}
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input3),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input3", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        placeholder: "Password",
                        size: "middle",
                        type: "password",
                        value: generateStateValueProp($state, [
                          "input3",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input3.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input3"}
                          data-plasmic-override={overrides.input3}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField___0Hc3Z
                    )}
                    label={
                      <LockSvgIcon
                        className={classNames(projectcss.all, sty.svg__hmebx)}
                        role={"img"}
                      />
                    }
                    name={"confirmpassword"}
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.input4),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["input4", "value"],
                            AntdInput_Helpers
                          ).apply(null, eventArgs);
                        },
                        placeholder: "Confirm Password",
                        size: "middle",
                        type: "password",
                        value: generateStateValueProp($state, [
                          "input4",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "input4.value"
                          }
                        ],
                        [],
                        AntdInput_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdInput
                          data-plasmic-name={"input4"}
                          data-plasmic-override={overrides.input4}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <div
                    data-plasmic-name={"errorText"}
                    data-plasmic-override={overrides.errorText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.errorText
                    )}
                  >
                    {"Invalid login credentials"}
                  </div>
                  <LoginButton
                    data-plasmic-name={"loginButton"}
                    data-plasmic-override={overrides.loginButton}
                    className={classNames("__wab_instance", sty.loginButton)}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vk2Nl
                      )}
                    >
                      {"Create account"}
                    </div>
                  </LoginButton>
                  <Checkbox
                    data-plasmic-name={"checkbox2"}
                    data-plasmic-override={overrides.checkbox2}
                    className={classNames("__wab_instance", sty.checkbox2)}
                    label={
                      <div
                        data-plasmic-name={"freeBox"}
                        data-plasmic-override={overrides.freeBox}
                        className={classNames(projectcss.all, sty.freeBox)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uc3Vt
                          )}
                        >
                          {"I accept the "}
                        </div>
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__kwYd
                          )}
                          component={Link}
                          platform={"nextjs"}
                        >
                          {"terms and conditions"}
                        </PlasmicLink__>
                      </div>
                    }
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "checkbox2",
                        "isSelected"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                  />
                </FormWrapper>
              );
            })()}
            <SignInWithGoogle
              data-plasmic-name={"signInWithGoogle"}
              data-plasmic-override={overrides.signInWithGoogle}
              className={classNames("__wab_instance", sty.signInWithGoogle)}
            />

            <div
              data-plasmic-name={"createAccount"}
              data-plasmic-override={overrides.createAccount}
              className={classNames(projectcss.all, sty.createAccount)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j3Au8
                )}
              >
                {"Already have account?"}
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__z76Ps
                )}
                component={Link}
                href={`/c-login`}
                platform={"nextjs"}
              >
                {"Log in"}
              </PlasmicLink__>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "img",
    "rectangle",
    "h6",
    "form2",
    "input2",
    "input3",
    "input4",
    "errorText",
    "loginButton",
    "checkbox2",
    "freeBox",
    "signInWithGoogle",
    "createAccount"
  ],
  img: ["img"],
  rectangle: [
    "rectangle",
    "h6",
    "form2",
    "input2",
    "input3",
    "input4",
    "errorText",
    "loginButton",
    "checkbox2",
    "freeBox",
    "signInWithGoogle",
    "createAccount"
  ],
  h6: ["h6"],
  form2: [
    "form2",
    "input2",
    "input3",
    "input4",
    "errorText",
    "loginButton",
    "checkbox2",
    "freeBox"
  ],
  input2: ["input2"],
  input3: ["input3"],
  input4: ["input4"],
  errorText: ["errorText"],
  loginButton: ["loginButton"],
  checkbox2: ["checkbox2", "freeBox"],
  freeBox: ["freeBox"],
  signInWithGoogle: ["signInWithGoogle"],
  createAccount: ["createAccount"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  rectangle: "div";
  h6: "h6";
  form2: typeof FormWrapper;
  input2: typeof AntdInput;
  input3: typeof AntdInput;
  input4: typeof AntdInput;
  errorText: "div";
  loginButton: typeof LoginButton;
  checkbox2: typeof Checkbox;
  freeBox: "div";
  signInWithGoogle: typeof SignInWithGoogle;
  createAccount: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLCCreateAccount__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLCCreateAccount__VariantsArgs;
    args?: PlasmicLCCreateAccount__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLCCreateAccount__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLCCreateAccount__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLCCreateAccount__ArgProps,
          internalVariantPropNames: PlasmicLCCreateAccount__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLCCreateAccount__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLCCreateAccount";
  } else {
    func.displayName = `PlasmicLCCreateAccount.${nodeName}`;
  }
  return func;
}

export const PlasmicLCCreateAccount = Object.assign(
  // Top-level PlasmicLCCreateAccount renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    rectangle: makeNodeComponent("rectangle"),
    h6: makeNodeComponent("h6"),
    form2: makeNodeComponent("form2"),
    input2: makeNodeComponent("input2"),
    input3: makeNodeComponent("input3"),
    input4: makeNodeComponent("input4"),
    errorText: makeNodeComponent("errorText"),
    loginButton: makeNodeComponent("loginButton"),
    checkbox2: makeNodeComponent("checkbox2"),
    freeBox: makeNodeComponent("freeBox"),
    signInWithGoogle: makeNodeComponent("signInWithGoogle"),
    createAccount: makeNodeComponent("createAccount"),

    // Metadata about props expected for PlasmicLCCreateAccount
    internalVariantProps: PlasmicLCCreateAccount__VariantProps,
    internalArgProps: PlasmicLCCreateAccount__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Create Account",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLCCreateAccount;
/* prettier-ignore-end */
