/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: XPcejG1cRAQD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: XPcejG1cRAQD/css

createPlasmicElementProxy;

export type PlasmicHomepage2__VariantMembers = {};
export type PlasmicHomepage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage2__VariantsArgs;
export const PlasmicHomepage2__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage2__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage2__ArgsType;
export const PlasmicHomepage2__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage2__OverridesType = {
  root?: Flex__<"div">;
  topBar?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
  container1?: Flex__<"div">;
  container3?: Flex__<"div">;
  container2?: Flex__<"div">;
  container4?: Flex__<"div">;
};

export interface DefaultHomepage2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage2__RenderFunc(props: {
  variants: PlasmicHomepage2__VariantsArgs;
  args: PlasmicHomepage2__ArgsType;
  overrides: PlasmicHomepage2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"topBar"}
            data-plasmic-override={overrides.topBar}
            className={classNames(projectcss.all, sty.topBar)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__gagNi)}>
              <div className={classNames(projectcss.all, sty.freeBox__g2Xfj)}>
                <NavigationBar
                  data-plasmic-name={"navigationBar"}
                  data-plasmic-override={overrides.navigationBar}
                  brand={
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uLgt4
                      )}
                      component={Link}
                      href={`/affiliate-homepage`}
                      legacyBehavior={false}
                      onClick={async event => {
                        const $steps = {};

                        $steps["refreshData"] = true
                          ? (() => {
                              const actionArgs = {
                                queryInvalidation: ["plasmic_refresh_all"]
                              };
                              return (async ({ queryInvalidation }) => {
                                if (!queryInvalidation) {
                                  return;
                                }
                                await plasmicInvalidate(queryInvalidation);
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["refreshData"] != null &&
                          typeof $steps["refreshData"] === "object" &&
                          typeof $steps["refreshData"].then === "function"
                        ) {
                          $steps["refreshData"] = await $steps["refreshData"];
                        }
                      }}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___8JDn)}
                        displayHeight={"30px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/ez_marketing_platform/images/logoPng2.png",
                          fullWidth: 190,
                          fullHeight: 100,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  }
                  className={classNames("__wab_instance", sty.navigationBar)}
                  closeButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tRnpa)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={"https://static1.plasmic.app/close.svg"}
                    />
                  }
                  itemsGap={8}
                  menuItems={
                    <React.Fragment>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___1UYfX
                        )}
                        component={Link}
                        href={"/"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Community Dashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__oNSe4
                        )}
                        component={Link}
                        href={"/"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Service\nDashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__zf36S
                        )}
                        component={Link}
                        href={"/"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Market\nTrends"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___3HpLw
                        )}
                        component={Link}
                        href={`/a-find-a-business`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Find a \nbusiness"}
                      </PlasmicLink__>
                    </React.Fragment>
                  }
                  openButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fVzOp)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      height={``}
                      src={"https://static1.plasmic.app/menu.svg"}
                      width={``}
                    />
                  }
                  responsiveBreakpoint={768}
                />

                <AntdDropdown
                  data-plasmic-name={"account"}
                  data-plasmic-override={overrides.account}
                  className={classNames("__wab_instance", sty.account)}
                  dropdownMenuScopeClassName={sty["account__dropdownMenu"]}
                  menuClassName={classNames({
                    [sty["pcls_e-CBTP0RHYXJ"]]: true
                  })}
                  menuItemClassName={classNames({
                    [sty["pcls_VS25SkJyOpb2"]]: true
                  })}
                  menuItems={() => (
                    <React.Fragment>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__oWusa
                        )}
                        key={"menu-item-1"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hivNx
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__qp4Qo
                        )}
                        key={"menu-item-2"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eC4Hr
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                    </React.Fragment>
                  )}
                  menuItemsJson={(() => {
                    const __composite = [
                      { type: null, label: null, children: null },
                      {
                        type: null,
                        value: "action1",
                        label: null,
                        children: null
                      },
                      {
                        type: null,
                        value: "action2",
                        label: null,
                        onClick: null
                      }
                    ];
                    __composite["0"]["type"] = "group";
                    __composite["0"]["label"] = "User";
                    __composite["0"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Profile";
                      __composite["0"]["onClick"] = async info => {
                        const $steps = {};

                        $steps["goToALogin"] = true
                          ? (() => {
                              const actionArgs = { destination: `/a-login` };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToALogin"] != null &&
                          typeof $steps["goToALogin"] === "object" &&
                          typeof $steps["goToALogin"].then === "function"
                        ) {
                          $steps["goToALogin"] = await $steps["goToALogin"];
                        }
                      };
                      __composite["1"]["label"] = "Edit profile";
                      __composite["1"]["onClick"] = async info => {
                        const $steps = {};

                        $steps["goToACreateAccount"] = true
                          ? (() => {
                              const actionArgs = {
                                destination: `/a-edit-profile`
                              };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToACreateAccount"] != null &&
                          typeof $steps["goToACreateAccount"] === "object" &&
                          typeof $steps["goToACreateAccount"].then ===
                            "function"
                        ) {
                          $steps["goToACreateAccount"] =
                            await $steps["goToACreateAccount"];
                        }
                      };
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["1"]["type"] = "group";
                    __composite["1"]["label"] = "Account";
                    __composite["1"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Settings & Privacy";
                      __composite["0"]["onClick"] = async info => {
                        const $steps = {};

                        $steps["goToALogin"] = true
                          ? (() => {
                              const actionArgs = { destination: `/a-login` };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToALogin"] != null &&
                          typeof $steps["goToALogin"] === "object" &&
                          typeof $steps["goToALogin"].then === "function"
                        ) {
                          $steps["goToALogin"] = await $steps["goToALogin"];
                        }
                      };
                      __composite["1"]["label"] = "Help";
                      __composite["1"]["onClick"] = async info => {
                        const $steps = {};

                        $steps["goToALogin"] = true
                          ? (() => {
                              const actionArgs = { destination: `/a-login` };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToALogin"] != null &&
                          typeof $steps["goToALogin"] === "object" &&
                          typeof $steps["goToALogin"].then === "function"
                        ) {
                          $steps["goToALogin"] = await $steps["goToALogin"];
                        }
                      };
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["2"]["type"] = "item";
                    __composite["2"]["label"] = "Sign out";
                    __composite["2"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    return __composite;
                  })()}
                  trigger={"hover"}
                  useMenuItemsSlot={false}
                >
                  <AntdButton
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    href={`/a-login`}
                    target={true}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pmRm6)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                    />
                  </AntdButton>
                </AntdDropdown>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"container1"}
            data-plasmic-override={overrides.container1}
            className={classNames(projectcss.all, sty.container1)}
          />

          <div
            data-plasmic-name={"container3"}
            data-plasmic-override={overrides.container3}
            className={classNames(projectcss.all, sty.container3)}
          />

          <div
            data-plasmic-name={"container2"}
            data-plasmic-override={overrides.container2}
            className={classNames(projectcss.all, sty.container2)}
          />

          <div
            data-plasmic-name={"container4"}
            data-plasmic-override={overrides.container4}
            className={classNames(projectcss.all, sty.container4)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBar",
    "navigationBar",
    "account",
    "button",
    "container1",
    "container3",
    "container2",
    "container4"
  ],
  topBar: ["topBar", "navigationBar", "account", "button"],
  navigationBar: ["navigationBar"],
  account: ["account", "button"],
  button: ["button"],
  container1: ["container1"],
  container3: ["container3"],
  container2: ["container2"],
  container4: ["container4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBar: "div";
  navigationBar: typeof NavigationBar;
  account: typeof AntdDropdown;
  button: typeof AntdButton;
  container1: "div";
  container3: "div";
  container2: "div";
  container4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage2__VariantsArgs;
    args?: PlasmicHomepage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage2__ArgProps,
          internalVariantPropNames: PlasmicHomepage2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBar: makeNodeComponent("topBar"),
    navigationBar: makeNodeComponent("navigationBar"),
    account: makeNodeComponent("account"),
    button: makeNodeComponent("button"),
    container1: makeNodeComponent("container1"),
    container3: makeNodeComponent("container3"),
    container2: makeNodeComponent("container2"),
    container4: makeNodeComponent("container4"),

    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
