/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: V_SPIj-8cNzM

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Modal from "../../Modal"; // plasmic-import: Hu0RbpkquL8l/component
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button2 from "../../Button2"; // plasmic-import: xUW1L309f0s-/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicUAnalysisAtCustomerLocation.module.css"; // plasmic-import: V_SPIj-8cNzM/css

import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: SO0iXB8RSj3u/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4JgiKKNVUuUK/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qQ9FpkDVW9kl/icon
import UserSvgIcon from "./icons/PlasmicIcon__UserSvg"; // plasmic-import: -m2qayguHrPf/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Confirm order",

    openGraph: {
      title: "Confirm order"
    },
    twitter: {
      card: "summary",
      title: "Confirm order"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicUAnalysisAtCustomerLocation__VariantMembers = {};
export type PlasmicUAnalysisAtCustomerLocation__VariantsArgs = {};
type VariantPropType = keyof PlasmicUAnalysisAtCustomerLocation__VariantsArgs;
export const PlasmicUAnalysisAtCustomerLocation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUAnalysisAtCustomerLocation__ArgsType = {
  eMailInput3?: React.ReactNode;
  eMailInput2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicUAnalysisAtCustomerLocation__ArgsType;
export const PlasmicUAnalysisAtCustomerLocation__ArgProps =
  new Array<ArgPropType>("eMailInput3", "eMailInput2");

export type PlasmicUAnalysisAtCustomerLocation__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  rectangle?: Flex__<"div">;
  solution?: Flex__<"div">;
  textArea?: Flex__<typeof AntdTextArea>;
  comeToAddress?: Flex__<"div">;
  modal?: Flex__<typeof Modal>;
  h3?: Flex__<"h3">;
  reviewRequest?: Flex__<typeof Modal>;
};

export interface DefaultUAnalysisAtCustomerLocationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUAnalysisAtCustomerLocation__RenderFunc(props: {
  variants: PlasmicUAnalysisAtCustomerLocation__VariantsArgs;
  args: PlasmicUAnalysisAtCustomerLocation__ArgsType;
  overrides: PlasmicUAnalysisAtCustomerLocation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "modal.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "reviewRequest.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"auto"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "400px"
                : "700px"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
              fullWidth: 297,
              fullHeight: 210,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"rectangle"}
            data-plasmic-override={overrides.rectangle}
            className={classNames(projectcss.all, sty.rectangle)}
          >
            <div
              data-plasmic-name={"solution"}
              data-plasmic-override={overrides.solution}
              className={classNames(projectcss.all, sty.solution)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rEhDv
                )}
              >
                {"Solution"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ndXvB)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jc9Ts
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy "
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ekv9Z)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bkhT
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c3Gw
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vs2Vi
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9LNnk
                    )}
                  >
                    {"[step]"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xt2J2
                )}
              >
                {"Any comments?"}
              </div>
              {(() => {
                const child$Props = {
                  bordered: true,
                  className: classNames("__wab_instance", sty.textArea),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["textArea", "value"],
                      AntdTextArea_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["textArea", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "textArea.value"
                    }
                  ],
                  [],
                  AntdTextArea_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdTextArea
                    data-plasmic-name={"textArea"}
                    data-plasmic-override={overrides.textArea}
                    {...child$Props}
                  />
                );
              })()}
            </div>
            <div
              data-plasmic-name={"comeToAddress"}
              data-plasmic-override={overrides.comeToAddress}
              className={classNames(projectcss.all, sty.comeToAddress)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rBzna
                )}
              >
                {"Come to address"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bqtEw)}>
                <_14655891761535698998SvgIcon
                  className={classNames(projectcss.all, sty.svg__tpzxb)}
                  role={"img"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__fL285)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7EB5V
                    )}
                  >
                    {"R. Uruguai, 244"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tXCqq
                    )}
                  >
                    {"Jadim Alvorada"}
                  </div>
                </div>
                <Modal
                  data-plasmic-name={"modal"}
                  data-plasmic-override={overrides.modal}
                  className={classNames("__wab_instance", sty.modal)}
                  content={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bo5Lu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9HWwQ
                        )}
                      >
                        <_14655891761535698998SvgIcon
                          className={classNames(projectcss.all, sty.svg__srqNv)}
                          role={"img"}
                        />

                        {renderPlasmicSlot({
                          defaultContents: (() => {
                            const child$Props = {
                              autoFocus: false,
                              bordered: true,
                              className: classNames(
                                "__wab_instance",
                                sty.input__e2Siu
                              ),
                              placeholder: "Address and number",
                              readOnly: false,
                              size: "middle",
                              type: "text"
                            };

                            return <AntdInput {...child$Props} />;
                          })(),
                          value: args.eMailInput3,
                          className: classNames(sty.slotTargetEMailInput3)
                        })}
                      </div>
                    </div>
                  }
                  footer={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h1Xn)}
                    >
                      <Button2
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__udbex
                            )}
                          >
                            {"Close"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["modal", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        type={"soft"}
                      />
                    </div>
                  }
                  heading={
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"Addresses"}
                    </h3>
                  }
                  isOpen={generateStateValueProp($state, ["modal", "isOpen"])}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "modal",
                      "isOpen"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  trigger={
                    <LoginButton
                      className={classNames(
                        "__wab_instance",
                        sty.loginButton___1RFyd
                      )}
                      size={"compact"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kIdBn
                        )}
                      >
                        {"Change"}
                      </div>
                    </LoginButton>
                  }
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___9TGv1)}>
              <UserSvgIcon
                className={classNames(projectcss.all, sty.svg__thQof)}
                role={"img"}
              />

              {renderPlasmicSlot({
                defaultContents: (() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input__aoL9I),
                    placeholder: "Email",
                    readOnly: false,
                    size: "middle",
                    type: "email"
                  };

                  return <AntdInput {...child$Props} />;
                })(),
                value: args.eMailInput2,
                className: classNames(sty.slotTargetEMailInput2)
              })}
            </div>
            <Modal
              data-plasmic-name={"reviewRequest"}
              data-plasmic-override={overrides.reviewRequest}
              className={classNames("__wab_instance", sty.reviewRequest)}
              content={
                <div
                  className={classNames(projectcss.all, sty.freeBox___3Jncu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__d8Ruh)}
                  >
                    <_14655891761535698998SvgIcon
                      className={classNames(projectcss.all, sty.svg___6COb)}
                      role={"img"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jVJli)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mw0Zj
                        )}
                      >
                        {"R. Uruguai, 244"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__psotM
                        )}
                      >
                        {"Jadim Alvorada"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iyQdM
                    )}
                  >
                    {"Solution"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__saMRr
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy "
                    }
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aDnNl)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rCrq
                      )}
                    >
                      {"U$"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ii5BE
                      )}
                    >
                      {"700,00"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aCgT
                    )}
                  >
                    {"carlos_galindo@hotmail.com"}
                  </div>
                </div>
              }
              footer={
                <div className={classNames(projectcss.all, sty.freeBox__ngRzc)}>
                  <Button2
                    color={"muted"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kos4W
                        )}
                      >
                        {"Cancel"}
                      </div>
                    }
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateModalIsOpen"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["reviewRequest", "isOpen"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateModalIsOpen"] != null &&
                        typeof $steps["updateModalIsOpen"] === "object" &&
                        typeof $steps["updateModalIsOpen"].then === "function"
                      ) {
                        $steps["updateModalIsOpen"] =
                          await $steps["updateModalIsOpen"];
                      }
                    }}
                    type={"soft"}
                  />

                  <LoginButton
                    className={classNames(
                      "__wab_instance",
                      sty.loginButton__risNt
                    )}
                    onClick={async event => {
                      const $steps = {};

                      $steps["goToUAnalysisAtCustomerLocationConfirmService"] =
                        true
                          ? (() => {
                              const actionArgs = {
                                destination: `/u-analysis-at-customer-location-confirm`
                              };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                      if (
                        $steps[
                          "goToUAnalysisAtCustomerLocationConfirmService"
                        ] != null &&
                        typeof $steps[
                          "goToUAnalysisAtCustomerLocationConfirmService"
                        ] === "object" &&
                        typeof $steps[
                          "goToUAnalysisAtCustomerLocationConfirmService"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToUAnalysisAtCustomerLocationConfirmService"
                        ] =
                          await $steps[
                            "goToUAnalysisAtCustomerLocationConfirmService"
                          ];
                      }
                    }}
                    size={"compact"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x0QrU
                      )}
                    >
                      {"Confirm"}
                    </div>
                  </LoginButton>
                </div>
              }
              heading={null}
              isOpen={generateStateValueProp($state, [
                "reviewRequest",
                "isOpen"
              ])}
              onOpenChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "reviewRequest",
                  "isOpen"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              trigger={
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__rq4Rd
                  )}
                  size={"compact"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fQpYy
                    )}
                  >
                    {"Review request"}
                  </div>
                </LoginButton>
              }
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "img",
    "rectangle",
    "solution",
    "textArea",
    "comeToAddress",
    "modal",
    "h3",
    "reviewRequest"
  ],
  img: ["img"],
  rectangle: [
    "rectangle",
    "solution",
    "textArea",
    "comeToAddress",
    "modal",
    "h3",
    "reviewRequest"
  ],
  solution: ["solution", "textArea"],
  textArea: ["textArea"],
  comeToAddress: ["comeToAddress", "modal", "h3"],
  modal: ["modal", "h3"],
  h3: ["h3"],
  reviewRequest: ["reviewRequest"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  rectangle: "div";
  solution: "div";
  textArea: typeof AntdTextArea;
  comeToAddress: "div";
  modal: typeof Modal;
  h3: "h3";
  reviewRequest: typeof Modal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUAnalysisAtCustomerLocation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUAnalysisAtCustomerLocation__VariantsArgs;
    args?: PlasmicUAnalysisAtCustomerLocation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicUAnalysisAtCustomerLocation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicUAnalysisAtCustomerLocation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUAnalysisAtCustomerLocation__ArgProps,
          internalVariantPropNames:
            PlasmicUAnalysisAtCustomerLocation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUAnalysisAtCustomerLocation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUAnalysisAtCustomerLocation";
  } else {
    func.displayName = `PlasmicUAnalysisAtCustomerLocation.${nodeName}`;
  }
  return func;
}

export const PlasmicUAnalysisAtCustomerLocation = Object.assign(
  // Top-level PlasmicUAnalysisAtCustomerLocation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    rectangle: makeNodeComponent("rectangle"),
    solution: makeNodeComponent("solution"),
    textArea: makeNodeComponent("textArea"),
    comeToAddress: makeNodeComponent("comeToAddress"),
    modal: makeNodeComponent("modal"),
    h3: makeNodeComponent("h3"),
    reviewRequest: makeNodeComponent("reviewRequest"),

    // Metadata about props expected for PlasmicUAnalysisAtCustomerLocation
    internalVariantProps: PlasmicUAnalysisAtCustomerLocation__VariantProps,
    internalArgProps: PlasmicUAnalysisAtCustomerLocation__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/u-analysis-at-customer-location",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicUAnalysisAtCustomerLocation;
/* prettier-ignore-end */
