/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: HlxSu33GdlWc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdProgress } from "@plasmicpkgs/antd5/skinny/registerProgress";
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicUAnalysisAtCustomerLocationConfirmService.module.css"; // plasmic-import: HlxSu33GdlWc/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon
import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: SO0iXB8RSj3u/icon

createPlasmicElementProxy;

export type PlasmicUAnalysisAtCustomerLocationConfirmService__VariantMembers =
  {};
export type PlasmicUAnalysisAtCustomerLocationConfirmService__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicUAnalysisAtCustomerLocationConfirmService__VariantsArgs;
export const PlasmicUAnalysisAtCustomerLocationConfirmService__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUAnalysisAtCustomerLocationConfirmService__ArgsType = {};
type ArgPropType =
  keyof PlasmicUAnalysisAtCustomerLocationConfirmService__ArgsType;
export const PlasmicUAnalysisAtCustomerLocationConfirmService__ArgProps =
  new Array<ArgPropType>();

export type PlasmicUAnalysisAtCustomerLocationConfirmService__OverridesType = {
  root?: Flex__<"div">;
  progress?: Flex__<typeof AntdProgress>;
  rectangle?: Flex__<"div">;
  loginButton?: Flex__<typeof LoginButton>;
  solution?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  svg?: Flex__<"svg">;
};

export interface DefaultUAnalysisAtCustomerLocationConfirmServiceProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUAnalysisAtCustomerLocationConfirmService__RenderFunc(props: {
  variants: PlasmicUAnalysisAtCustomerLocationConfirmService__VariantsArgs;
  args: PlasmicUAnalysisAtCustomerLocationConfirmService__ArgsType;
  overrides: PlasmicUAnalysisAtCustomerLocationConfirmService__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicUAnalysisAtCustomerLocationConfirmService.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={
            PlasmicUAnalysisAtCustomerLocationConfirmService.pageMetadata.title
          }
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={
            PlasmicUAnalysisAtCustomerLocationConfirmService.pageMetadata.title
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3___2W61X
            )}
          >
            {"Awaiting confirmation"}
          </h3>
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3__bRms
            )}
          >
            {"Confirmed"}
          </h3>
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3___7V8Xk
            )}
          >
            {"On the way"}
          </h3>
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3__dW5Js
            )}
          >
            {"Problem with address"}
          </h3>
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3__frOqh
            )}
          >
            {"Canceled"}
          </h3>
          <h3
            className={classNames(
              projectcss.all,
              projectcss.h3,
              projectcss.__wab_text,
              sty.h3__oZhZw
            )}
          >
            {"Canceled with fee"}
          </h3>
          <AntdProgress
            data-plasmic-name={"progress"}
            data-plasmic-override={overrides.progress}
            className={classNames("__wab_instance", sty.progress)}
            percent={50}
            showInfo={false}
            size={"small"}
            status={"normal"}
            stepColors={[{}, {}]}
            strokeLinecap={"square"}
            successPercent={0}
            type={"line"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hsNd8
            )}
          >
            {"10:20"}
          </div>
          <div
            data-plasmic-name={"rectangle"}
            data-plasmic-override={overrides.rectangle}
            className={classNames(projectcss.all, sty.rectangle)}
          >
            <LoginButton
              data-plasmic-name={"loginButton"}
              data-plasmic-override={overrides.loginButton}
              className={classNames("__wab_instance", sty.loginButton)}
              color={"red"}
              onClick={async event => {
                const $steps = {};
              }}
              size={"compact"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sX7G
                )}
              >
                {"Cancel service"}
              </div>
            </LoginButton>
            <div
              data-plasmic-name={"solution"}
              data-plasmic-override={overrides.solution}
              className={classNames(projectcss.all, sty.solution)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__j0NoQ)}>
                <PlasmicImg__
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(sty.img)}
                  displayHeight={"30px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"30px"}
                  loading={"lazy"}
                />

                <PlasmicLink__
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  platform={"nextjs"}
                >
                  {"Company"}
                </PlasmicLink__>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uefZh
                )}
              >
                {"Solution"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yXv8J)}>
                <_14655891761535698998SvgIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__nnzQc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r2Qw7
                    )}
                  >
                    {"R. Uruguai, 244"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6VC3R
                    )}
                  >
                    {"Jadim Alvorada"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xnHnz
                )}
              >
                {"carlos_galindo@hotmail.com"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "progress",
    "rectangle",
    "loginButton",
    "solution",
    "img",
    "link",
    "svg"
  ],
  progress: ["progress"],
  rectangle: ["rectangle", "loginButton", "solution", "img", "link", "svg"],
  loginButton: ["loginButton"],
  solution: ["solution", "img", "link", "svg"],
  img: ["img"],
  link: ["link"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  progress: typeof AntdProgress;
  rectangle: "div";
  loginButton: typeof LoginButton;
  solution: "div";
  img: typeof PlasmicImg__;
  link: "a";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUAnalysisAtCustomerLocationConfirmService__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUAnalysisAtCustomerLocationConfirmService__VariantsArgs;
    args?: PlasmicUAnalysisAtCustomerLocationConfirmService__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<
      PlasmicUAnalysisAtCustomerLocationConfirmService__VariantsArgs,
      ReservedPropsType
    > &
    // Specify args directly as props
    Omit<
      PlasmicUAnalysisAtCustomerLocationConfirmService__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicUAnalysisAtCustomerLocationConfirmService__ArgProps,
          internalVariantPropNames:
            PlasmicUAnalysisAtCustomerLocationConfirmService__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUAnalysisAtCustomerLocationConfirmService__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUAnalysisAtCustomerLocationConfirmService";
  } else {
    func.displayName = `PlasmicUAnalysisAtCustomerLocationConfirmService.${nodeName}`;
  }
  return func;
}

export const PlasmicUAnalysisAtCustomerLocationConfirmService = Object.assign(
  // Top-level PlasmicUAnalysisAtCustomerLocationConfirmService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    progress: makeNodeComponent("progress"),
    rectangle: makeNodeComponent("rectangle"),
    loginButton: makeNodeComponent("loginButton"),
    solution: makeNodeComponent("solution"),
    img: makeNodeComponent("img"),
    link: makeNodeComponent("link"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicUAnalysisAtCustomerLocationConfirmService
    internalVariantProps:
      PlasmicUAnalysisAtCustomerLocationConfirmService__VariantProps,
    internalArgProps:
      PlasmicUAnalysisAtCustomerLocationConfirmService__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Order tracking",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicUAnalysisAtCustomerLocationConfirmService;
/* prettier-ignore-end */
