/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: 0Ds1kmUVD8RK

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { AntdSteps } from "@plasmicpkgs/antd5/skinny/registerSteps";
import { UploadWrapper } from "@plasmicpkgs/antd5/skinny/registerUpload";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdOption } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicACreateCommunity.module.css"; // plasmic-import: 0Ds1kmUVD8RK/css

import FinanceSvgrepoComSvgIcon from "./icons/PlasmicIcon__FinanceSvgrepoComSvg"; // plasmic-import: uZNeCpxTtFE5/icon
import UserSvgIcon from "./icons/PlasmicIcon__UserSvg"; // plasmic-import: -m2qayguHrPf/icon
import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: SO0iXB8RSj3u/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon
import YoutubeIconLogoSvgrepoComSvgIcon from "./icons/PlasmicIcon__YoutubeIconLogoSvgrepoComSvg"; // plasmic-import: vpgn9iumYsFp/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: Bvh42noj5uIh/icon
import IlustrgatuSvg2Icon from "./icons/PlasmicIcon__IlustrgatuSvg2"; // plasmic-import: iwxJHLaYior3/icon
import IlustrgatuSvgIcon from "./icons/PlasmicIcon__IlustrgatuSvg"; // plasmic-import: sz_dn1E8VLZT/icon
import GlobeSvgIcon from "./icons/PlasmicIcon__GlobeSvg"; // plasmic-import: 7r83p-4N-D3c/icon
import TrophySportsAndCompetitionSvgrepoComSvgIcon from "./icons/PlasmicIcon__TrophySportsAndCompetitionSvgrepoComSvg"; // plasmic-import: 4090DaEoSO38/icon

createPlasmicElementProxy;

export type PlasmicACreateCommunity__VariantMembers = {};
export type PlasmicACreateCommunity__VariantsArgs = {};
type VariantPropType = keyof PlasmicACreateCommunity__VariantsArgs;
export const PlasmicACreateCommunity__VariantProps =
  new Array<VariantPropType>();

export type PlasmicACreateCommunity__ArgsType = {};
type ArgPropType = keyof PlasmicACreateCommunity__ArgsType;
export const PlasmicACreateCommunity__ArgProps = new Array<ArgPropType>();

export type PlasmicACreateCommunity__OverridesType = {
  root?: Flex__<"div">;
  topBar?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account?: Flex__<typeof AntdDropdown>;
  rectangle?: Flex__<"div">;
  stepsStack?: Flex__<"div">;
  steps?: Flex__<typeof AntdSteps>;
  basicInfo?: Flex__<"div">;
  upload?: Flex__<typeof UploadWrapper>;
  select3?: Flex__<typeof AntdSelect>;
  input2?: Flex__<typeof AntdInput>;
  input3?: Flex__<typeof AntdInput>;
  links?: Flex__<"div">;
  input5?: Flex__<typeof AntdInput>;
  input6?: Flex__<typeof AntdInput>;
  input8?: Flex__<typeof AntdInput>;
  input7?: Flex__<typeof AntdInput>;
  skills?: Flex__<"div">;
  upload2?: Flex__<typeof UploadWrapper>;
  input9?: Flex__<typeof AntdInput>;
  input10?: Flex__<typeof AntdInput>;
  textArea?: Flex__<typeof AntdTextArea>;
};

export interface DefaultACreateCommunityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicACreateCommunity__RenderFunc(props: {
  variants: PlasmicACreateCommunity__VariantsArgs;
  args: PlasmicACreateCommunity__ArgsType;
  overrides: PlasmicACreateCommunity__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "steps.current",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.currentStep;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return 1;
              }
              throw e;
            }
          })()
      },
      {
        path: "upload.files",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      },
      {
        path: "input2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input5.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input6.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input7.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "currentStep",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "select3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "input8.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "upload2.files",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      },
      {
        path: "input9.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input10.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicACreateCommunity.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicACreateCommunity.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicACreateCommunity.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"topBar"}
          data-plasmic-override={overrides.topBar}
          className={classNames(projectcss.all, sty.topBar)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__abQqC)}>
            <div className={classNames(projectcss.all, sty.freeBox___2Lox4)}>
              <NavigationBar
                data-plasmic-name={"navigationBar"}
                data-plasmic-override={overrides.navigationBar}
                brand={
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ixVe6
                    )}
                    component={Link}
                    onClick={async event => {
                      const $steps = {};

                      $steps["refreshData"] = true
                        ? (() => {
                            const actionArgs = {
                              queryInvalidation: ["plasmic_refresh_all"]
                            };
                            return (async ({ queryInvalidation }) => {
                              if (!queryInvalidation) {
                                return;
                              }
                              await plasmicInvalidate(queryInvalidation);
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["refreshData"] != null &&
                        typeof $steps["refreshData"] === "object" &&
                        typeof $steps["refreshData"].then === "function"
                      ) {
                        $steps["refreshData"] = await $steps["refreshData"];
                      }
                    }}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hnuoz)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/ez_marketing_platform/images/ezSvg2.svg",
                        fullWidth: 60,
                        fullHeight: 31,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                }
                className={classNames("__wab_instance", sty.navigationBar)}
                closeButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xO3B7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/close.svg"}
                  />
                }
                itemsGap={8}
                menuItems={
                  <React.Fragment>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__hqfDn
                      )}
                      component={Link}
                      href={`/community-dashboard`}
                      platform={"nextjs"}
                    >
                      {"Community Dashboard"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__zx6O2
                      )}
                      component={Link}
                      href={`/service-dashboard`}
                      platform={"nextjs"}
                    >
                      {"Service\nDashboard"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___4ToPo
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Market\nTrends"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__jArAr
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Find a \nbusiness"}
                    </PlasmicLink__>
                  </React.Fragment>
                }
                openButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___3HWcd)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    height={``}
                    src={"https://static1.plasmic.app/menu.svg"}
                    width={``}
                  />
                }
                responsiveBreakpoint={768}
              />

              <AntdDropdown
                data-plasmic-name={"account"}
                data-plasmic-override={overrides.account}
                className={classNames("__wab_instance", sty.account)}
                dropdownMenuScopeClassName={sty["account__dropdownMenu"]}
                menuClassName={classNames({ [sty["pcls_jTXmwRk8-pvT"]]: true })}
                menuItemClassName={classNames({
                  [sty["pcls_mOoDSnlAmri3"]]: true
                })}
                menuItems={() => (
                  <React.Fragment>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__wkYV
                      )}
                      key={"menu-item-1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xmu8E
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__fTKtD
                      )}
                      key={"menu-item-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___74Mba
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                  </React.Fragment>
                )}
                menuItemsJson={(() => {
                  const __composite = [
                    { type: null, label: null, children: null },
                    {
                      type: null,
                      value: "action1",
                      label: null,
                      children: null
                    },
                    { type: null, value: "action2", label: null, onClick: null }
                  ];
                  __composite["0"]["type"] = "group";
                  __composite["0"]["label"] = "User";
                  __composite["0"]["children"] = (() => {
                    const __composite = [
                      { type: "item", label: null, onClick: null },
                      { type: "item", label: null, onClick: null },
                      { type: null }
                    ];
                    __composite["0"]["label"] = "Profile";
                    __composite["0"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToAProfile"] = true
                        ? (() => {
                            const actionArgs = { destination: `/profile` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToAProfile"] != null &&
                        typeof $steps["goToAProfile"] === "object" &&
                        typeof $steps["goToAProfile"].then === "function"
                      ) {
                        $steps["goToAProfile"] = await $steps["goToAProfile"];
                      }
                    };
                    __composite["1"]["label"] = "Edit profile";
                    __composite["1"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToACreateAccount"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: `/a-edit-profile`
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToACreateAccount"] != null &&
                        typeof $steps["goToACreateAccount"] === "object" &&
                        typeof $steps["goToACreateAccount"].then === "function"
                      ) {
                        $steps["goToACreateAccount"] =
                          await $steps["goToACreateAccount"];
                      }
                    };
                    __composite["2"]["type"] = "divider";
                    return __composite;
                  })();
                  __composite["1"]["type"] = "group";
                  __composite["1"]["label"] = "Account";
                  __composite["1"]["children"] = (() => {
                    const __composite = [
                      { type: "item", label: null, onClick: null },
                      { type: "item", label: null, onClick: null },
                      { type: null }
                    ];
                    __composite["0"]["label"] = "Settings & Privacy";
                    __composite["0"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    __composite["1"]["label"] = "Help";
                    __composite["1"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    __composite["2"]["type"] = "divider";
                    return __composite;
                  })();
                  __composite["2"]["type"] = "item";
                  __composite["2"]["label"] = "Sign out";
                  __composite["2"]["onClick"] = async info => {
                    const $steps = {};

                    $steps["goToALogin"] = true
                      ? (() => {
                          const actionArgs = { destination: `/a-login` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToALogin"] != null &&
                      typeof $steps["goToALogin"] === "object" &&
                      typeof $steps["goToALogin"].then === "function"
                    ) {
                      $steps["goToALogin"] = await $steps["goToALogin"];
                    }
                  };
                  return __composite;
                })()}
                trigger={"hover"}
                useMenuItemsSlot={false}
              >
                <AntdButton
                  className={classNames("__wab_instance", sty.button__rmmUu)}
                  href={`/a-login`}
                  target={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fkOhb)}
                    displayHeight={"30px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"30px"}
                    loading={"lazy"}
                  />
                </AntdButton>
              </AntdDropdown>
            </div>
          </div>
        </div>
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img___9Xz7V)}
          displayHeight={"100px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"auto"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? "400px"
              : "600px"
          }
          loading={"lazy"}
          src={{
            src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
            fullWidth: 297,
            fullHeight: 210,
            aspectRatio: undefined
          }}
        />

        <div
          data-plasmic-name={"rectangle"}
          data-plasmic-override={overrides.rectangle}
          className={classNames(projectcss.all, sty.rectangle)}
        >
          <div
            data-plasmic-name={"stepsStack"}
            data-plasmic-override={overrides.stepsStack}
            className={classNames(projectcss.all, sty.stepsStack)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__nE7R0)}>
              <section
                className={classNames(projectcss.all, sty.section__qDrJ9)}
              >
                <svg
                  className={classNames(projectcss.all, sty.svg__tEu6P)}
                  role={"img"}
                />
              </section>
              <AntdSteps
                data-plasmic-name={"steps"}
                data-plasmic-override={overrides.steps}
                className={classNames("__wab_instance", sty.steps)}
                current={generateStateValueProp($state, ["steps", "current"])}
                direction={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "horizontal"
                    : "vertical"
                }
                items={(() => {
                  const __composite = [
                    { title: null, disabled: null },
                    { title: null, disabled: null },
                    { title: null, disabled: null }
                  ];
                  __composite["0"]["title"] = "Basic info";
                  __composite["0"]["disabled"] = true;
                  __composite["1"]["title"] = "Links";
                  __composite["1"]["disabled"] = true;
                  __composite["2"]["title"] = "Agency info";
                  __composite["2"]["disabled"] = true;
                  return __composite;
                })()}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, ["steps", "current"]).apply(
                    null,
                    eventArgs
                  );
                }}
                progressDot={false}
                responsive={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? false
                    : false
                }
                size={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "small"
                    : "small"
                }
                status={"process"}
                type={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "default"
                    : "default"
                }
              />

              <section
                className={classNames(projectcss.all, sty.section__yyTd4)}
              />
            </div>
          </div>
          {(() => {
            try {
              return $state.currentStep === 0;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div
              data-plasmic-name={"basicInfo"}
              data-plasmic-override={overrides.basicInfo}
              className={classNames(projectcss.all, sty.basicInfo)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zvQf6
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__joh9C
                      )}
                    >
                      {"Edit community"}
                    </h6>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__oFDvN)}>
                <UploadWrapper
                  data-plasmic-name={"upload"}
                  data-plasmic-override={overrides.upload}
                  accept={"image/*"}
                  className={classNames("__wab_instance", sty.upload)}
                  files={generateStateValueProp($state, ["upload", "files"])}
                  listType={"picture-circle"}
                  maxCount={1}
                  onFilesChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "upload",
                      "files"
                    ]).apply(null, eventArgs);
                  }}
                  showUploadList={false}
                >
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__tsybg)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fXbpZ
                      )}
                    >
                      {"Upload"}
                    </div>
                  </AntdButton>
                </UploadWrapper>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eUwYb
                  )}
                >
                  {"Put a community pic"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lZ)}>
                <FinanceSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg___7NsTd)}
                  role={"img"}
                />

                <AntdSelect
                  data-plasmic-name={"select3"}
                  data-plasmic-override={overrides.select3}
                  allowClear={true}
                  autoFocus={false}
                  bordered={true}
                  className={classNames("__wab_instance", sty.select3)}
                  defaultOpen={false}
                  defaultStylesClassName={classNames(
                    projectcss.root_reset,
                    projectcss.plasmic_default_styles,
                    projectcss.plasmic_mixins,
                    styleTokensClassNames
                  )}
                  dropdownMatchSelectWidth={false}
                  mode={"single"}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "select3",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  options={(() => {
                    const __composite = [
                      { type: "option", label: null, value: null },
                      { type: "option", label: null, value: null },
                      { type: "option", label: null, value: null }
                    ];
                    __composite["0"]["label"] = "Creative Director";
                    __composite["0"]["value"] = "aaaaaa";
                    __composite["1"]["label"] = "Art Director";
                    __composite["1"]["value"] = "value";
                    __composite["2"]["label"] = "Graphic Designer";
                    __composite["2"]["value"] = "sssssssssssss";
                    return __composite;
                  })()}
                  placeholder={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hMqUz
                      )}
                    >
                      {"What will your relationship with companies be like?"}
                    </div>
                  }
                  popupScopeClassName={sty["select3__popup"]}
                  showSearch={false}
                  size={"middle"}
                  useChildren={true}
                  value={generateStateValueProp($state, ["select3", "value"])}
                >
                  <AntdOption
                    className={classNames("__wab_instance", sty.option__cnJVz)}
                    value={"Standard"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eqjHx
                      )}
                    >
                      {"Standard"}
                    </div>
                  </AntdOption>
                  <AntdOption
                    className={classNames("__wab_instance", sty.option__suXli)}
                    value={"Venture"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kiuf4
                      )}
                    >
                      {"Venture"}
                    </div>
                  </AntdOption>
                </AntdSelect>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___9Vq8E)}>
                <UserSvgIcon
                  className={classNames(projectcss.all, sty.svg__wvKcH)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input2),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input2", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Community name",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input2", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input2.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input2"}
                      data-plasmic-override={overrides.input2}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bX7Te)}>
                <_14655891761535698998SvgIcon
                  className={classNames(projectcss.all, sty.svg__g8H9)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input3),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input3", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Location (optional)",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input3", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input3.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input3"}
                      data-plasmic-override={overrides.input3}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <LoginButton
                className={classNames("__wab_instance", sty.loginButton__e2QAq)}
                onClick={async event => {
                  const $steps = {};

                  $steps["runCode"] = true
                    ? (() => {
                        const actionArgs = {
                          customFunction: async () => {
                            return ($state.currentStep += 1);
                          }
                        };
                        return (({ customFunction }) => {
                          return customFunction();
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runCode"] != null &&
                    typeof $steps["runCode"] === "object" &&
                    typeof $steps["runCode"].then === "function"
                  ) {
                    $steps["runCode"] = await $steps["runCode"];
                  }
                }}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ofyE
                  )}
                >
                  {"Next"}
                </div>
              </LoginButton>
            </div>
          ) : null}
          {(() => {
            try {
              return $state.currentStep === 1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div
              data-plasmic-name={"links"}
              data-plasmic-override={overrides.links}
              className={classNames(projectcss.all, sty.links)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ykrP
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__w6Hn
                      )}
                    >
                      {"Agency links"}
                    </h6>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ucwJ9)}>
                <YoutubeIconLogoSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__tV2Id)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input5),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input5", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "YouTube channel",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input5", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input5.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input5"}
                      data-plasmic-override={overrides.input5}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__w0R9C)}>
                <Icon6Icon
                  className={classNames(projectcss.all, sty.svg__jWMc)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input6),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input6", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Instagram",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input6", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input6.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input6"}
                      data-plasmic-override={overrides.input6}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__cgBe)}>
                <IlustrgatuSvg2Icon
                  className={classNames(projectcss.all, sty.svg__c2Lz4)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input8),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input8", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Tik tok",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input8", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input8.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input8"}
                      data-plasmic-override={overrides.input8}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___4ZW0)}>
                <IlustrgatuSvgIcon
                  className={classNames(projectcss.all, sty.svg__iwtgZ)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input7),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input7", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "X",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input7", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input7.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input7"}
                      data-plasmic-override={overrides.input7}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fMjxT)}>
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__noBx3
                  )}
                  color={"softSand"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return ($state.currentStep -= 1);
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8An0F
                    )}
                  >
                    {"Previous"}
                  </div>
                </LoginButton>
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__puZvh
                  )}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return ($state.currentStep += 1);
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cwEhr
                    )}
                  >
                    {"Next"}
                  </div>
                </LoginButton>
              </div>
            </div>
          ) : null}
          {(() => {
            try {
              return $state.currentStep === 2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div
              data-plasmic-name={"skills"}
              data-plasmic-override={overrides.skills}
              className={classNames(projectcss.all, sty.skills)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xCr35
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__taaEt
                      )}
                    >
                      {"Agency info"}
                    </h6>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___0Teb8)}>
                <UploadWrapper
                  data-plasmic-name={"upload2"}
                  data-plasmic-override={overrides.upload2}
                  accept={"image/*"}
                  className={classNames("__wab_instance", sty.upload2)}
                  files={generateStateValueProp($state, ["upload2", "files"])}
                  listType={"text"}
                  onFilesChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "upload2",
                      "files"
                    ]).apply(null, eventArgs);
                  }}
                  showUploadList={false}
                >
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__vaEwr)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vBrFs
                      )}
                    >
                      {"Upload"}
                    </div>
                  </AntdButton>
                </UploadWrapper>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zf2Qh
                  )}
                >
                  {
                    "(optional) Upload an image or GIF that showcases the agency's goals."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yqyWl)}>
                <YoutubeIconLogoSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__yCZ)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input9),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input9", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder:
                      "Present your agency in a video, use a YouTube link",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input9", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input9.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input9"}
                      data-plasmic-override={overrides.input9}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__hn1Wu)}>
                <GlobeSvgIcon
                  className={classNames(projectcss.all, sty.svg__rJcij)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input10),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input10", "value"],
                        AntdInput_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Agency official website",
                    readOnly: false,
                    size: "middle",
                    type: "text",
                    value: generateStateValueProp($state, ["input10", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "input10.value"
                      }
                    ],
                    [],
                    AntdInput_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdInput
                      data-plasmic-name={"input10"}
                      data-plasmic-override={overrides.input10}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rNOl)}>
                <TrophySportsAndCompetitionSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__pSp5A)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.textArea),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["textArea", "value"],
                        AntdTextArea_Helpers
                      ).apply(null, eventArgs);
                    },
                    placeholder: "Tell about your agency",
                    value: generateStateValueProp($state, ["textArea", "value"])
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "textArea.value"
                      }
                    ],
                    [],
                    AntdTextArea_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdTextArea
                      data-plasmic-name={"textArea"}
                      data-plasmic-override={overrides.textArea}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ohbqf)}>
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__xWeAs
                  )}
                  color={"softSand"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return ($state.currentStep -= 1);
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tW8ON
                    )}
                  >
                    {"Previous"}
                  </div>
                </LoginButton>
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__bpTo3
                  )}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToACommunityDashboard"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: `/community-dashboard`
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToACommunityDashboard"] != null &&
                      typeof $steps["goToACommunityDashboard"] === "object" &&
                      typeof $steps["goToACommunityDashboard"].then ===
                        "function"
                    ) {
                      $steps["goToACommunityDashboard"] =
                        await $steps["goToACommunityDashboard"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aIt1O
                    )}
                  >
                    {"Done"}
                  </div>
                </LoginButton>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBar",
    "navigationBar",
    "account",
    "rectangle",
    "stepsStack",
    "steps",
    "basicInfo",
    "upload",
    "select3",
    "input2",
    "input3",
    "links",
    "input5",
    "input6",
    "input8",
    "input7",
    "skills",
    "upload2",
    "input9",
    "input10",
    "textArea"
  ],
  topBar: ["topBar", "navigationBar", "account"],
  navigationBar: ["navigationBar"],
  account: ["account"],
  rectangle: [
    "rectangle",
    "stepsStack",
    "steps",
    "basicInfo",
    "upload",
    "select3",
    "input2",
    "input3",
    "links",
    "input5",
    "input6",
    "input8",
    "input7",
    "skills",
    "upload2",
    "input9",
    "input10",
    "textArea"
  ],
  stepsStack: ["stepsStack", "steps"],
  steps: ["steps"],
  basicInfo: ["basicInfo", "upload", "select3", "input2", "input3"],
  upload: ["upload"],
  select3: ["select3"],
  input2: ["input2"],
  input3: ["input3"],
  links: ["links", "input5", "input6", "input8", "input7"],
  input5: ["input5"],
  input6: ["input6"],
  input8: ["input8"],
  input7: ["input7"],
  skills: ["skills", "upload2", "input9", "input10", "textArea"],
  upload2: ["upload2"],
  input9: ["input9"],
  input10: ["input10"],
  textArea: ["textArea"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBar: "div";
  navigationBar: typeof NavigationBar;
  account: typeof AntdDropdown;
  rectangle: "div";
  stepsStack: "div";
  steps: typeof AntdSteps;
  basicInfo: "div";
  upload: typeof UploadWrapper;
  select3: typeof AntdSelect;
  input2: typeof AntdInput;
  input3: typeof AntdInput;
  links: "div";
  input5: typeof AntdInput;
  input6: typeof AntdInput;
  input8: typeof AntdInput;
  input7: typeof AntdInput;
  skills: "div";
  upload2: typeof UploadWrapper;
  input9: typeof AntdInput;
  input10: typeof AntdInput;
  textArea: typeof AntdTextArea;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicACreateCommunity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicACreateCommunity__VariantsArgs;
    args?: PlasmicACreateCommunity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicACreateCommunity__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicACreateCommunity__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicACreateCommunity__ArgProps,
          internalVariantPropNames: PlasmicACreateCommunity__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicACreateCommunity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicACreateCommunity";
  } else {
    func.displayName = `PlasmicACreateCommunity.${nodeName}`;
  }
  return func;
}

export const PlasmicACreateCommunity = Object.assign(
  // Top-level PlasmicACreateCommunity renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBar: makeNodeComponent("topBar"),
    navigationBar: makeNodeComponent("navigationBar"),
    account: makeNodeComponent("account"),
    rectangle: makeNodeComponent("rectangle"),
    stepsStack: makeNodeComponent("stepsStack"),
    steps: makeNodeComponent("steps"),
    basicInfo: makeNodeComponent("basicInfo"),
    upload: makeNodeComponent("upload"),
    select3: makeNodeComponent("select3"),
    input2: makeNodeComponent("input2"),
    input3: makeNodeComponent("input3"),
    links: makeNodeComponent("links"),
    input5: makeNodeComponent("input5"),
    input6: makeNodeComponent("input6"),
    input8: makeNodeComponent("input8"),
    input7: makeNodeComponent("input7"),
    skills: makeNodeComponent("skills"),
    upload2: makeNodeComponent("upload2"),
    input9: makeNodeComponent("input9"),
    input10: makeNodeComponent("input10"),
    textArea: makeNodeComponent("textArea"),

    // Metadata about props expected for PlasmicACreateCommunity
    internalVariantProps: PlasmicACreateCommunity__VariantProps,
    internalArgProps: PlasmicACreateCommunity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Create Community",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicACreateCommunity;
/* prettier-ignore-end */
