/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: VpQf35B-PWeJ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Modal from "../../Modal"; // plasmic-import: Hu0RbpkquL8l/component
import { AntdRate } from "@plasmicpkgs/antd5/skinny/registerRate";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button2 from "../../Button2"; // plasmic-import: xUW1L309f0s-/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicCRateACommunitie.module.css"; // plasmic-import: VpQf35B-PWeJ/css

import SemTitulo1SvgIcon from "./icons/PlasmicIcon__SemTitulo1Svg"; // plasmic-import: k_BH6L3djmDT/icon
import CustomerKnowledgeSvgIcon from "./icons/PlasmicIcon__CustomerKnowledgeSvg"; // plasmic-import: qnB1jD3GOdBV/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 4JgiKKNVUuUK/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qQ9FpkDVW9kl/icon
import YourAverageRateSvgIcon from "./icons/PlasmicIcon__YourAverageRateSvg"; // plasmic-import: 62l9CNk3G8rK/icon
import CustomerRatesSvgIcon from "./icons/PlasmicIcon__CustomerRatesSvg"; // plasmic-import: 0K6hwUE1S6a9/icon

createPlasmicElementProxy;

export type PlasmicCRateACommunitie__VariantMembers = {};
export type PlasmicCRateACommunitie__VariantsArgs = {};
type VariantPropType = keyof PlasmicCRateACommunitie__VariantsArgs;
export const PlasmicCRateACommunitie__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCRateACommunitie__ArgsType = {};
type ArgPropType = keyof PlasmicCRateACommunitie__ArgsType;
export const PlasmicCRateACommunitie__ArgProps = new Array<ArgPropType>();

export type PlasmicCRateACommunitie__OverridesType = {
  root?: Flex__<"div">;
  topBar?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
  container3?: Flex__<"div">;
  communityLogo?: Flex__<typeof PlasmicImg__>;
  type?: Flex__<"svg">;
  communityName?: Flex__<"div">;
  sliderCarousel2?: Flex__<typeof SliderWrapper>;
  member?: Flex__<"div">;
  office?: Flex__<"div">;
  profilePic?: Flex__<typeof PlasmicImg__>;
  rateThisAgency?: Flex__<"div">;
  actualData?: Flex__<"div">;
  rate?: Flex__<typeof Modal>;
  rating?: Flex__<typeof AntdRate>;
  h3?: Flex__<"h3">;
  comment?: Flex__<typeof AntdTextArea>;
  confirmRate?: Flex__<typeof Button2>;
  button2?: Flex__<typeof Button2>;
  agencysRate?: Flex__<typeof AntdRate>;
  rateSum?: Flex__<"div">;
  customerRated?: Flex__<typeof AntdRate>;
  rateSum2?: Flex__<"div">;
  reportRate?: Flex__<"div">;
  reportData?: Flex__<"div">;
  customerInstruction?: Flex__<typeof AntdRate>;
  agencyRate?: Flex__<typeof AntdRate>;
  averageRatingReceived?: Flex__<typeof AntdRate>;
};

export interface DefaultCRateACommunitieProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCRateACommunitie__RenderFunc(props: {
  variants: PlasmicCRateACommunitie__VariantsArgs;
  args: PlasmicCRateACommunitie__ArgsType;
  overrides: PlasmicCRateACommunitie__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "rate.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "rating.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "comment.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "agencysRate.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "customerRated.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      },
      {
        path: "agencyRate.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "customerInstruction.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "averageRatingReceived.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicCRateACommunitie.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicCRateACommunitie.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicCRateACommunitie.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"topBar"}
          data-plasmic-override={overrides.topBar}
          className={classNames(projectcss.all, sty.topBar)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__d8L0H)}>
            <div className={classNames(projectcss.all, sty.freeBox__uPkA2)}>
              <NavigationBar
                data-plasmic-name={"navigationBar"}
                data-plasmic-override={overrides.navigationBar}
                brand={
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__mtv6M
                    )}
                    component={Link}
                    href={`/corporative-page`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__sgGpN)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/ez_marketing_platform/images/ezSvg2.svg",
                        fullWidth: 60,
                        fullHeight: 31,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                }
                className={classNames("__wab_instance", sty.navigationBar)}
                closeButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___1Ywzq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/close.svg"}
                  />
                }
                itemsGap={8}
                menuItems={
                  <React.Fragment>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___3A9Qg
                      )}
                      component={Link}
                      href={`/company-profile`}
                      platform={"nextjs"}
                    >
                      {"Company\nprofile"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__bmQyg
                      )}
                      component={Link}
                      href={`/services-dashboard`}
                      platform={"nextjs"}
                    >
                      {"Service\nDashboard"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__m9EIp
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Market\nTrends"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__rWtNk
                      )}
                      component={Link}
                      href={`/find-a-affiliate`}
                      platform={"nextjs"}
                    >
                      {"Find a \naffiliate"}
                    </PlasmicLink__>
                  </React.Fragment>
                }
                openButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___0JXjN)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    height={``}
                    src={"https://static1.plasmic.app/menu.svg"}
                    width={``}
                  />
                }
                responsiveBreakpoint={768}
              />

              <AntdDropdown
                data-plasmic-name={"account"}
                data-plasmic-override={overrides.account}
                className={classNames("__wab_instance", sty.account)}
                dropdownMenuScopeClassName={sty["account__dropdownMenu"]}
                menuItems={() => (
                  <React.Fragment>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem___3EjxZ
                      )}
                      key={"menu-item-1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9Ug0G
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem___8OocV
                      )}
                      key={"menu-item-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3MQmo
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                  </React.Fragment>
                )}
                menuItemsJson={(() => {
                  const __composite = [
                    {
                      type: null,
                      value: "action1",
                      label: null,
                      children: null
                    },
                    {
                      type: null,
                      value: "action2",
                      label: null,
                      onClick: null
                    },
                    { type: "item" }
                  ];
                  __composite["0"]["type"] = "group";
                  __composite["0"]["label"] = "Account";
                  __composite["0"]["children"] = (() => {
                    const __composite = [
                      { type: "item", label: null, onClick: null },
                      { type: "item", label: null, onClick: null },
                      { type: null }
                    ];
                    __composite["0"]["label"] = "Settings & Privacy";
                    __composite["1"]["label"] = "Help";
                    __composite["2"]["type"] = "divider";
                    return __composite;
                  })();
                  __composite["1"]["type"] = "item";
                  __composite["1"]["label"] = "Sign out";
                  return __composite;
                })()}
                trigger={"hover"}
                useMenuItemsSlot={false}
              >
                <AntdButton
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  target={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__rN9T6)}
                    displayHeight={"30px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"30px"}
                    loading={"lazy"}
                  />
                </AntdButton>
              </AntdDropdown>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container3"}
          data-plasmic-override={overrides.container3}
          className={classNames(projectcss.all, sty.container3)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__uyog)}>
            <PlasmicImg__
              data-plasmic-name={"communityLogo"}
              data-plasmic-override={overrides.communityLogo}
              alt={""}
              className={classNames(sty.communityLogo)}
              displayHeight={"100px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/ez_marketing_platform/images/semTitulo2Jpg3.jpg",
                fullWidth: 1014,
                fullHeight: 1014,
                aspectRatio: undefined
              }}
            />

            <SemTitulo1SvgIcon
              data-plasmic-name={"type"}
              data-plasmic-override={overrides.type}
              className={classNames(projectcss.all, sty.type)}
              role={"img"}
            />

            <div
              data-plasmic-name={"communityName"}
              data-plasmic-override={overrides.communityName}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.communityName
              )}
            >
              {"Community"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___0SJmh)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dhR4V
              )}
            >
              {"Gold"}
            </div>
            {(() => {
              const child$Props = {
                adaptiveHeight: false,
                arrows: false,
                beforeChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "currentSlide",
                    ["sliderCarousel2", "currentSlide"],
                    SliderWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                centerMode: false,
                className: classNames("__wab_instance", sty.sliderCarousel2),
                dots: true,
                fade: true,
                focusOnSelect: true,
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel2",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel2"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel2__slider"],
                slidesPerRow: 4
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel2.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel2"}
                  data-plasmic-override={overrides.sliderCarousel2}
                  {...child$Props}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tB60P)}
                  >
                    <div
                      data-plasmic-name={"member"}
                      data-plasmic-override={overrides.member}
                      className={classNames(projectcss.all, sty.member)}
                    >
                      <div
                        data-plasmic-name={"office"}
                        data-plasmic-override={overrides.office}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.office
                        )}
                      >
                        {"Market Mananger"}
                      </div>
                      <PlasmicImg__
                        data-plasmic-name={"profilePic"}
                        data-plasmic-override={overrides.profilePic}
                        alt={""}
                        className={classNames(sty.profilePic)}
                        displayHeight={"150px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"120px"}
                        src={{
                          src: "/plasmic/ez_marketing_platform/images/vecteezyUserAccountIconForYourDesignOnly21079672Png.png",
                          fullWidth: 2551,
                          fullHeight: 2551,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qrjTk
                        )}
                      >
                        {"Gold"}
                      </div>
                    </div>
                  </div>
                </SliderWrapper>
              );
            })()}
          </div>
        </div>
        <div
          data-plasmic-name={"rateThisAgency"}
          data-plasmic-override={overrides.rateThisAgency}
          className={classNames(projectcss.all, sty.rateThisAgency)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yQdlU
            )}
          >
            {"Rate this agency"}
          </div>
          <div
            data-plasmic-name={"actualData"}
            data-plasmic-override={overrides.actualData}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.actualData
            )}
          >
            {"07/2025 - 10/2025"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xcjm8)}>
            <div className={classNames(projectcss.all, sty.freeBox__py3R)}>
              <CustomerKnowledgeSvgIcon
                className={classNames(projectcss.all, sty.svg__rpXh)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iAJjB
                )}
              >
                {
                  "Do the clients from that agency know what they're signing up for?\r\n\r"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__il87Y
                )}
              >
                {
                  "Rate if the clients are well-versed in the available service, getting straight to the point, without any pretensions."
                }
              </div>
              <Modal
                data-plasmic-name={"rate"}
                data-plasmic-override={overrides.rate}
                className={classNames("__wab_instance", sty.rate)}
                content={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dv97)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yup1
                      )}
                    >
                      {
                        "Help other companies know if it's good to work with this agency by leaving a comment."
                      }
                    </div>
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.comment),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["comment", "value"],
                            AntdTextArea_Helpers
                          ).apply(null, eventArgs);
                        },
                        value: generateStateValueProp($state, [
                          "comment",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "comment.value"
                          }
                        ],
                        [],
                        AntdTextArea_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdTextArea
                          data-plasmic-name={"comment"}
                          data-plasmic-override={overrides.comment}
                          {...child$Props}
                        />
                      );
                    })()}
                  </div>
                }
                footer={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aTvUr)}
                  >
                    <Button2
                      data-plasmic-name={"confirmRate"}
                      data-plasmic-override={overrides.confirmRate}
                      color={"muted"}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o5Yu9
                          )}
                        >
                          {"Confirm"}
                        </div>
                      }
                      size={"extraSmall"}
                      type={"soft"}
                    />

                    <Button2
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      color={"muted"}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6Tv6U
                          )}
                        >
                          {"Cancel"}
                        </div>
                      }
                      size={"extraSmall"}
                      type={"soft"}
                    />
                  </div>
                }
                heading={
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {"Rating"}
                  </h3>
                }
                isOpen={generateStateValueProp($state, ["rate", "isOpen"])}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, ["rate", "isOpen"]).apply(
                    null,
                    eventArgs
                  );

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                trigger={
                  <AntdRate
                    data-plasmic-name={"rating"}
                    data-plasmic-override={overrides.rating}
                    allowHalf={true}
                    className={classNames("__wab_instance", sty.rating)}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "rating",
                        "value"
                      ]).apply(null, eventArgs);
                    }}
                    symbols={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tKjp3
                          )}
                        >
                          {"1"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__g5Hwg
                          )}
                        >
                          {"2"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jI2En
                          )}
                        >
                          {"3"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cOFle
                          )}
                        >
                          {"4"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hhQg
                          )}
                        >
                          {"5"}
                        </div>
                      </React.Fragment>
                    }
                    value={generateStateValueProp($state, ["rating", "value"])}
                  />
                }
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__swJr4)}>
              <YourAverageRateSvgIcon
                className={classNames(projectcss.all, sty.svg__sOPdj)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tse43
                )}
              >
                {"Rating received by the agency"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qkYqU
                )}
              >
                {
                  "This agency has given your company a rating based on its performance over the last three months."
                }
              </div>
              <AntdRate
                data-plasmic-name={"agencysRate"}
                data-plasmic-override={overrides.agencysRate}
                allowHalf={true}
                className={classNames("__wab_instance", sty.agencysRate)}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "agencysRate",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lVeVe
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rpabw
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qiTfl
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lblpc
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fhp4Z
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, ["agencysRate", "value"])}
              />

              <div
                data-plasmic-name={"rateSum"}
                data-plasmic-override={overrides.rateSum}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.rateSum
                )}
              >
                {"(50)"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___23Rw)}>
              <CustomerRatesSvgIcon
                className={classNames(projectcss.all, sty.svg__fhSjt)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5O7Mu
                )}
              >
                {"What clients from the agency rated you"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dLsZ
                )}
              >
                {
                  "The clients this agency sent to you rated your service overall over the last three months, with an average of"
                }
              </div>
              <AntdRate
                data-plasmic-name={"customerRated"}
                data-plasmic-override={overrides.customerRated}
                allowHalf={true}
                className={classNames("__wab_instance", sty.customerRated)}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "customerRated",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iWv1J
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fd9Sy
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tBpXq
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hCReI
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cuIvq
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, [
                  "customerRated",
                  "value"
                ])}
              />

              <div
                data-plasmic-name={"rateSum2"}
                data-plasmic-override={overrides.rateSum2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.rateSum2
                )}
              >
                {"(50)"}
              </div>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__aMxay)}>
          <div className={classNames(projectcss.all, sty.freeBox__nsCrT)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zoAhs
              )}
            >
              {"Enter some text"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__pEds4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dgcPi
                )}
              >
                {"Customer instruction"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6HMlw
                )}
              >
                {"Agency rating"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hteLv
                )}
              >
                {"Average rating received"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"reportRate"}
            data-plasmic-override={overrides.reportRate}
            className={classNames(projectcss.all, sty.reportRate)}
          >
            <div
              data-plasmic-name={"reportData"}
              data-plasmic-override={overrides.reportData}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.reportData
              )}
            >
              {"07/2025 - 10/2025"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__iSpWm)}>
              <AntdRate
                data-plasmic-name={"customerInstruction"}
                data-plasmic-override={overrides.customerInstruction}
                allowHalf={true}
                className={classNames(
                  "__wab_instance",
                  sty.customerInstruction
                )}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "customerInstruction",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kUaUe
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f8QsE
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vdvCs
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uwF
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x4OWj
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, [
                  "customerInstruction",
                  "value"
                ])}
              />

              <AntdRate
                data-plasmic-name={"agencyRate"}
                data-plasmic-override={overrides.agencyRate}
                allowHalf={true}
                className={classNames("__wab_instance", sty.agencyRate)}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "agencyRate",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gRwih
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ou11V
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__c2NN
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dyuFh
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tsY5F
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, ["agencyRate", "value"])}
              />

              <AntdRate
                data-plasmic-name={"averageRatingReceived"}
                data-plasmic-override={overrides.averageRatingReceived}
                allowHalf={true}
                className={classNames(
                  "__wab_instance",
                  sty.averageRatingReceived
                )}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "averageRatingReceived",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__usxiP
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__keAtG
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0C1Xq
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jIZvd
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__urEkn
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, [
                  "averageRatingReceived",
                  "value"
                ])}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBar",
    "navigationBar",
    "account",
    "button",
    "container3",
    "communityLogo",
    "type",
    "communityName",
    "sliderCarousel2",
    "member",
    "office",
    "profilePic",
    "rateThisAgency",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "agencysRate",
    "rateSum",
    "customerRated",
    "rateSum2",
    "reportRate",
    "reportData",
    "customerInstruction",
    "agencyRate",
    "averageRatingReceived"
  ],
  topBar: ["topBar", "navigationBar", "account", "button"],
  navigationBar: ["navigationBar"],
  account: ["account", "button"],
  button: ["button"],
  container3: [
    "container3",
    "communityLogo",
    "type",
    "communityName",
    "sliderCarousel2",
    "member",
    "office",
    "profilePic"
  ],
  communityLogo: ["communityLogo"],
  type: ["type"],
  communityName: ["communityName"],
  sliderCarousel2: ["sliderCarousel2", "member", "office", "profilePic"],
  member: ["member", "office", "profilePic"],
  office: ["office"],
  profilePic: ["profilePic"],
  rateThisAgency: [
    "rateThisAgency",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "agencysRate",
    "rateSum",
    "customerRated",
    "rateSum2"
  ],
  actualData: ["actualData"],
  rate: ["rate", "rating", "h3", "comment", "confirmRate", "button2"],
  rating: ["rating"],
  h3: ["h3"],
  comment: ["comment"],
  confirmRate: ["confirmRate"],
  button2: ["button2"],
  agencysRate: ["agencysRate"],
  rateSum: ["rateSum"],
  customerRated: ["customerRated"],
  rateSum2: ["rateSum2"],
  reportRate: [
    "reportRate",
    "reportData",
    "customerInstruction",
    "agencyRate",
    "averageRatingReceived"
  ],
  reportData: ["reportData"],
  customerInstruction: ["customerInstruction"],
  agencyRate: ["agencyRate"],
  averageRatingReceived: ["averageRatingReceived"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBar: "div";
  navigationBar: typeof NavigationBar;
  account: typeof AntdDropdown;
  button: typeof AntdButton;
  container3: "div";
  communityLogo: typeof PlasmicImg__;
  type: "svg";
  communityName: "div";
  sliderCarousel2: typeof SliderWrapper;
  member: "div";
  office: "div";
  profilePic: typeof PlasmicImg__;
  rateThisAgency: "div";
  actualData: "div";
  rate: typeof Modal;
  rating: typeof AntdRate;
  h3: "h3";
  comment: typeof AntdTextArea;
  confirmRate: typeof Button2;
  button2: typeof Button2;
  agencysRate: typeof AntdRate;
  rateSum: "div";
  customerRated: typeof AntdRate;
  rateSum2: "div";
  reportRate: "div";
  reportData: "div";
  customerInstruction: typeof AntdRate;
  agencyRate: typeof AntdRate;
  averageRatingReceived: typeof AntdRate;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCRateACommunitie__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCRateACommunitie__VariantsArgs;
    args?: PlasmicCRateACommunitie__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCRateACommunitie__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCRateACommunitie__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCRateACommunitie__ArgProps,
          internalVariantPropNames: PlasmicCRateACommunitie__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCRateACommunitie__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCRateACommunitie";
  } else {
    func.displayName = `PlasmicCRateACommunitie.${nodeName}`;
  }
  return func;
}

export const PlasmicCRateACommunitie = Object.assign(
  // Top-level PlasmicCRateACommunitie renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBar: makeNodeComponent("topBar"),
    navigationBar: makeNodeComponent("navigationBar"),
    account: makeNodeComponent("account"),
    button: makeNodeComponent("button"),
    container3: makeNodeComponent("container3"),
    communityLogo: makeNodeComponent("communityLogo"),
    type: makeNodeComponent("type"),
    communityName: makeNodeComponent("communityName"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    member: makeNodeComponent("member"),
    office: makeNodeComponent("office"),
    profilePic: makeNodeComponent("profilePic"),
    rateThisAgency: makeNodeComponent("rateThisAgency"),
    actualData: makeNodeComponent("actualData"),
    rate: makeNodeComponent("rate"),
    rating: makeNodeComponent("rating"),
    h3: makeNodeComponent("h3"),
    comment: makeNodeComponent("comment"),
    confirmRate: makeNodeComponent("confirmRate"),
    button2: makeNodeComponent("button2"),
    agencysRate: makeNodeComponent("agencysRate"),
    rateSum: makeNodeComponent("rateSum"),
    customerRated: makeNodeComponent("customerRated"),
    rateSum2: makeNodeComponent("rateSum2"),
    reportRate: makeNodeComponent("reportRate"),
    reportData: makeNodeComponent("reportData"),
    customerInstruction: makeNodeComponent("customerInstruction"),
    agencyRate: makeNodeComponent("agencyRate"),
    averageRatingReceived: makeNodeComponent("averageRatingReceived"),

    // Metadata about props expected for PlasmicCRateACommunitie
    internalVariantProps: PlasmicCRateACommunitie__VariantProps,
    internalArgProps: PlasmicCRateACommunitie__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Rate a community",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCRateACommunitie;
/* prettier-ignore-end */
