/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: yNx9gF4FHivD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicLANewPassword.module.css"; // plasmic-import: yNx9gF4FHivD/css

import LockSvgIcon from "./icons/PlasmicIcon__LockSvg"; // plasmic-import: qjaD0kAu4SMs/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon

createPlasmicElementProxy;

export type PlasmicLANewPassword__VariantMembers = {};
export type PlasmicLANewPassword__VariantsArgs = {};
type VariantPropType = keyof PlasmicLANewPassword__VariantsArgs;
export const PlasmicLANewPassword__VariantProps = new Array<VariantPropType>();

export type PlasmicLANewPassword__ArgsType = {};
type ArgPropType = keyof PlasmicLANewPassword__ArgsType;
export const PlasmicLANewPassword__ArgProps = new Array<ArgPropType>();

export type PlasmicLANewPassword__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  rectangle?: Flex__<"div">;
  h6?: Flex__<"h6">;
  form?: Flex__<typeof FormWrapper>;
  password?: Flex__<typeof AntdPassword>;
  confirmPassword?: Flex__<typeof AntdPassword>;
  errorText?: Flex__<"div">;
  loginButton?: Flex__<typeof LoginButton>;
};

export interface DefaultLANewPasswordProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLANewPassword__RenderFunc(props: {
  variants: PlasmicLANewPassword__VariantsArgs;
  args: PlasmicLANewPassword__ArgsType;
  overrides: PlasmicLANewPassword__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      },
      {
        path: "confirmPassword.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicLANewPassword.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicLANewPassword.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicLANewPassword.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"auto"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "400px"
                : "700px"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
              fullWidth: 297,
              fullHeight: 210,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"rectangle"}
            data-plasmic-override={overrides.rectangle}
            className={classNames(projectcss.all, sty.rectangle)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lYlXo
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h6
                    data-plasmic-name={"h6"}
                    data-plasmic-override={overrides.h6}
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6
                    )}
                  >
                    {"Create a new password"}
                  </h6>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            {(() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.form),
                extendedOnValuesChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "value",
                    ["form", "value"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                formItems: [
                  { label: "Name", name: "name", inputType: "Text" },
                  { label: "Message", name: "message", inputType: "Text Area" }
                ],
                labelAlign: "left",
                labelCol: (() => {
                  const __composite = {
                    span: null,
                    horizontalOnly: true,
                    offset: null
                  };
                  __composite["span"] = 2;
                  __composite["offset"] = 0;
                  return __composite;
                })(),

                layout: "horizontal",
                mode: "advanced",
                onIsSubmittingChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "isSubmitting",
                    ["form", "isSubmitting"],
                    FormWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                ref: ref => {
                  $refs["form"] = ref;
                },
                submitSlot: null,
                wrapperCol: (() => {
                  const __composite = { span: null, horizontalOnly: true };
                  __composite["span"] = 22;
                  return __composite;
                })()
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "value",
                    plasmicStateName: "form.value"
                  },
                  {
                    name: "isSubmitting",
                    plasmicStateName: "form.isSubmitting"
                  }
                ],
                [],
                FormWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <FormWrapper
                  data-plasmic-name={"form"}
                  data-plasmic-override={overrides.form}
                  {...child$Props}
                >
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__sFaaR
                    )}
                    label={
                      <LockSvgIcon
                        className={classNames(projectcss.all, sty.svg__fKziq)}
                        role={"img"}
                      />
                    }
                    name={"password"}
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.password),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["password", "value"],
                            AntdPassword_Helpers
                          ).apply(null, eventArgs);
                        },
                        placeholder: "New password",
                        value: generateStateValueProp($state, [
                          "password",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "password.value"
                          }
                        ],
                        [],
                        AntdPassword_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdPassword
                          data-plasmic-name={"password"}
                          data-plasmic-override={overrides.password}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <FormItemWrapper
                    className={classNames(
                      "__wab_instance",
                      sty.formField__pSvFp
                    )}
                    label={
                      <LockSvgIcon
                        className={classNames(projectcss.all, sty.svg__c8Uak)}
                        role={"img"}
                      />
                    }
                    name={"confirmpassword"}
                  >
                    {(() => {
                      const child$Props = {
                        className: classNames(
                          "__wab_instance",
                          sty.confirmPassword
                        ),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["confirmPassword", "value"],
                            AntdPassword_Helpers
                          ).apply(null, eventArgs);
                        },
                        placeholder: "Confirm password",
                        value: generateStateValueProp($state, [
                          "confirmPassword",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "confirmPassword.value"
                          }
                        ],
                        [],
                        AntdPassword_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdPassword
                          data-plasmic-name={"confirmPassword"}
                          data-plasmic-override={overrides.confirmPassword}
                          {...child$Props}
                        />
                      );
                    })()}
                  </FormItemWrapper>
                  <div
                    data-plasmic-name={"errorText"}
                    data-plasmic-override={overrides.errorText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.errorText
                    )}
                  >
                    {"Invalid login credentials"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0GkW
                    )}
                  >
                    {"Passwords must match"}
                  </div>
                  <LoginButton
                    data-plasmic-name={"loginButton"}
                    data-plasmic-override={overrides.loginButton}
                    className={classNames("__wab_instance", sty.loginButton)}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dWpNj
                      )}
                    >
                      {"Save new password"}
                    </div>
                  </LoginButton>
                </FormWrapper>
              );
            })()}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "img",
    "rectangle",
    "h6",
    "form",
    "password",
    "confirmPassword",
    "errorText",
    "loginButton"
  ],
  img: ["img"],
  rectangle: [
    "rectangle",
    "h6",
    "form",
    "password",
    "confirmPassword",
    "errorText",
    "loginButton"
  ],
  h6: ["h6"],
  form: ["form", "password", "confirmPassword", "errorText", "loginButton"],
  password: ["password"],
  confirmPassword: ["confirmPassword"],
  errorText: ["errorText"],
  loginButton: ["loginButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  rectangle: "div";
  h6: "h6";
  form: typeof FormWrapper;
  password: typeof AntdPassword;
  confirmPassword: typeof AntdPassword;
  errorText: "div";
  loginButton: typeof LoginButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLANewPassword__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLANewPassword__VariantsArgs;
    args?: PlasmicLANewPassword__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLANewPassword__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLANewPassword__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLANewPassword__ArgProps,
          internalVariantPropNames: PlasmicLANewPassword__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLANewPassword__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLANewPassword";
  } else {
    func.displayName = `PlasmicLANewPassword.${nodeName}`;
  }
  return func;
}

export const PlasmicLANewPassword = Object.assign(
  // Top-level PlasmicLANewPassword renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    rectangle: makeNodeComponent("rectangle"),
    h6: makeNodeComponent("h6"),
    form: makeNodeComponent("form"),
    password: makeNodeComponent("password"),
    confirmPassword: makeNodeComponent("confirmPassword"),
    errorText: makeNodeComponent("errorText"),
    loginButton: makeNodeComponent("loginButton"),

    // Metadata about props expected for PlasmicLANewPassword
    internalVariantProps: PlasmicLANewPassword__VariantProps,
    internalArgProps: PlasmicLANewPassword__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Enter a new password",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLANewPassword;
/* prettier-ignore-end */
