/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: maKqnX1RyE1vKUCrTH51ZZ
// Component: FejO9v2ox89B

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import LoginButton from "../../LoginButton"; // plasmic-import: EirQVSsAP1l8/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import FooterSection from "../../FooterSection"; // plasmic-import: AywyFyH1Vzu_/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: maKqnX1RyE1vKUCrTH51ZZ/projectcss
import sty from "./PlasmicCLandingPageContact.module.css"; // plasmic-import: FejO9v2ox89B/css

import UserSvgIcon from "./icons/PlasmicIcon__UserSvg"; // plasmic-import: -m2qayguHrPf/icon
import BriefcaseSvgIcon from "./icons/PlasmicIcon__BriefcaseSvg"; // plasmic-import: e4z9f03eViXR/icon
import _4654364831553230929SvgIcon from "./icons/PlasmicIcon___4654364831553230929Svg"; // plasmic-import: gGFr9WIusHWQ/icon
import GlobeSvgIcon from "./icons/PlasmicIcon__GlobeSvg"; // plasmic-import: 7r83p-4N-D3c/icon
import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: 2CF1JK7pRFx7/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 24lxsqUjkbYM/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: GHhSOYXBnYhK/icon

createPlasmicElementProxy;

export type PlasmicCLandingPageContact__VariantMembers = {};
export type PlasmicCLandingPageContact__VariantsArgs = {};
type VariantPropType = keyof PlasmicCLandingPageContact__VariantsArgs;
export const PlasmicCLandingPageContact__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCLandingPageContact__ArgsType = {};
type ArgPropType = keyof PlasmicCLandingPageContact__ArgsType;
export const PlasmicCLandingPageContact__ArgProps = new Array<ArgPropType>();

export type PlasmicCLandingPageContact__OverridesType = {
  root?: Flex__<"div">;
  formulario1?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  h2?: Flex__<"h2">;
  form?: Flex__<typeof FormWrapper>;
  input7?: Flex__<typeof AntdInput>;
  input11?: Flex__<typeof AntdInput>;
  input12?: Flex__<typeof AntdInput>;
  input13?: Flex__<typeof AntdInput>;
  input14?: Flex__<typeof AntdInput>;
  loginButton?: Flex__<typeof LoginButton>;
  input?: Flex__<typeof AntdInput>;
  embedHtml?: Flex__<typeof Embed>;
  footerSection?: Flex__<typeof FooterSection>;
  metaPixel?: Flex__<typeof Embed>;
};

export interface DefaultCLandingPageContactProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCLandingPageContact__RenderFunc(props: {
  variants: PlasmicCLandingPageContact__VariantsArgs;
  args: PlasmicCLandingPageContact__ArgsType;
  overrides: PlasmicCLandingPageContact__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input7.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input11.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input12.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input13.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input14.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"formulario1"}
            data-plasmic-override={overrides.formulario1}
            className={classNames(projectcss.all, sty.formulario1)}
          >
            <div className={classNames(projectcss.all, sty.column__vd5Dx)}>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"100%"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/ez_marketing_platform/images/business2879499640Jpg.jpg",
                  fullWidth: 640,
                  fullHeight: 423,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__pzMg)}>
              <h2
                data-plasmic-name={"h2"}
                data-plasmic-override={overrides.h2}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2
                )}
              >
                {"Secure Your Place on the Waiting List!"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xiLfw
                )}
              >
                {
                  "Be one of the first companies to access this revolution in digital marketing.\r\n\nFill in your details below:"
                }
              </div>
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.form),
                  extendedOnValuesChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["form", "value"],
                      FormWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  formItems: [
                    { label: "Name", name: "name", inputType: "Text" },
                    {
                      label: "Message",
                      name: "message",
                      inputType: "Text Area"
                    }
                  ],
                  labelCol: (() => {
                    const __composite = { span: null, horizontalOnly: true };
                    __composite["span"] = 2;
                    return __composite;
                  })(),

                  layout: "horizontal",
                  mode: "advanced",
                  onFinish: async values => {
                    const $steps = {};
                  },
                  onIsSubmittingChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "isSubmitting",
                      ["form", "isSubmitting"],
                      FormWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  ref: ref => {
                    $refs["form"] = ref;
                  },
                  submitSlot: null,
                  wrapperCol: { span: 16, horizontalOnly: true }
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "form.value"
                    },
                    {
                      name: "isSubmitting",
                      plasmicStateName: "form.isSubmitting"
                    }
                  ],
                  [],
                  FormWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <FormWrapper
                    data-plasmic-name={"form"}
                    data-plasmic-override={overrides.form}
                    {...child$Props}
                  >
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__t4A4
                      )}
                      initialValue={undefined}
                      label={
                        <UserSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Ecji
                          )}
                          role={"img"}
                        />
                      }
                      name={"Name"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input7),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input7", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "Name",
                          value: generateStateValueProp($state, [
                            "input7",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input7.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input7"}
                            data-plasmic-override={overrides.input7}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__wqMf6
                      )}
                      initialValue={undefined}
                      label={
                        <BriefcaseSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3YcAx
                          )}
                          role={"img"}
                        />
                      }
                      name={"Company"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input11),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input11", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "Company",
                          value: generateStateValueProp($state, [
                            "input11",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input11.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input11"}
                            data-plasmic-override={overrides.input11}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__wxfza
                      )}
                      initialValue={undefined}
                      label={
                        <_4654364831553230929SvgIcon
                          className={classNames(projectcss.all, sty.svg__lwvza)}
                          role={"img"}
                        />
                      }
                      name={"email"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input12),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input12", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "email",
                          value: generateStateValueProp($state, [
                            "input12",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input12.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input12"}
                            data-plasmic-override={overrides.input12}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField___0ENpr
                      )}
                      initialValue={undefined}
                      label={
                        <GlobeSvgIcon
                          className={classNames(projectcss.all, sty.svg__uB6Ch)}
                          role={"img"}
                        />
                      }
                      name={"Website"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input13),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input13", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "website",
                          value: generateStateValueProp($state, [
                            "input13",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input13.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input13"}
                            data-plasmic-override={overrides.input13}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__mfE8Z
                      )}
                      initialValue={undefined}
                      label={
                        <SearchSvgIcon
                          className={classNames(projectcss.all, sty.svg__s173N)}
                          role={"img"}
                        />
                      }
                      name={"What other platform do you use?"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input14),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input14", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          placeholder: "What other platform do you use?",
                          value: generateStateValueProp($state, [
                            "input14",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input14.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input14"}
                            data-plasmic-override={overrides.input14}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                    <LoginButton
                      data-plasmic-name={"loginButton"}
                      data-plasmic-override={overrides.loginButton}
                      className={classNames("__wab_instance", sty.loginButton)}
                      onClick={async event => {
                        const $steps = {};
                      }}
                      shape={"rounded"}
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hyAz2
                        )}
                      >
                        {"Get in wait list"}
                      </div>
                    </LoginButton>
                    <FormItemWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.formField__h0FXe
                      )}
                      hidden={true}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qz7Ta
                          )}
                        >
                          {"Label"}
                        </div>
                      }
                      name={"captcha_token"}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.input),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["input", "value"],
                              AntdInput_Helpers
                            ).apply(null, eventArgs);
                          },
                          value: generateStateValueProp($state, [
                            "input",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "input.value"
                            }
                          ],
                          [],
                          AntdInput_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdInput
                            data-plasmic-name={"input"}
                            data-plasmic-override={overrides.input}
                            {...child$Props}
                          />
                        );
                      })()}
                    </FormItemWrapper>
                  </FormWrapper>
                );
              })()}
            </div>
          </div>
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script>\r\n  document.addEventListener("DOMContentLoaded", function() {\r\n    const form = document.querySelector("form");\r\n    if (form) {\r\n      form.addEventListener("submit", function(e) {\r\n        const token = grecaptcha.getResponse();\r\n        if (!token) {\r\n          alert("Please tick the reCAPTCHA");\r\n          e.preventDefault();\r\n          e.stopImmediatePropagation();\r\n          return false;\r\n        }\r\n        // Preenche o hidden input\r\n        document.querySelector(\'input[name="captcha_token"]\').value = token;\r\n\r\n        // Pequeno delay pra garantir envio do Supabase\r\n        setTimeout(function() {\r\n          window.location.href = "/thank-you";\r\n        }, 300);\r\n      });\r\n    }\r\n  });\r\n</script>\r\n\r\n\r\n'
            }
          />

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />

          <Embed
            data-plasmic-name={"metaPixel"}
            data-plasmic-override={overrides.metaPixel}
            className={classNames("__wab_instance", sty.metaPixel)}
            code={
              "<!-- Meta Pixel Code -->\r\n<script>\r\n!function(f,b,e,v,n,t,s)\r\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\r\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\r\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\r\nn.queue=[];t=b.createElement(e);t.async=!0;\r\nt.src=v;s=b.getElementsByTagName(e)[0];\r\ns.parentNode.insertBefore(t,s)}(window, document,'script',\r\n'https://connect.facebook.net/en_US/fbevents.js');\r\nfbq('init', '294590235435738');\r\nfbq('track', 'PageView');\r\n</script>\r\n<noscript><img height=\"1\" width=\"1\" style=\"display:none\"\r\nsrc=\"https://www.facebook.com/tr?id=294590235435738&ev=PageView&noscript=1\"\r\n/></noscript>\r\n<!-- End Meta Pixel Code -->\r\n\r\n"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "formulario1",
    "img",
    "h2",
    "form",
    "input7",
    "input11",
    "input12",
    "input13",
    "input14",
    "loginButton",
    "input",
    "embedHtml",
    "footerSection",
    "metaPixel"
  ],
  formulario1: [
    "formulario1",
    "img",
    "h2",
    "form",
    "input7",
    "input11",
    "input12",
    "input13",
    "input14",
    "loginButton",
    "input"
  ],
  img: ["img"],
  h2: ["h2"],
  form: [
    "form",
    "input7",
    "input11",
    "input12",
    "input13",
    "input14",
    "loginButton",
    "input"
  ],
  input7: ["input7"],
  input11: ["input11"],
  input12: ["input12"],
  input13: ["input13"],
  input14: ["input14"],
  loginButton: ["loginButton"],
  input: ["input"],
  embedHtml: ["embedHtml"],
  footerSection: ["footerSection"],
  metaPixel: ["metaPixel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  formulario1: "div";
  img: typeof PlasmicImg__;
  h2: "h2";
  form: typeof FormWrapper;
  input7: typeof AntdInput;
  input11: typeof AntdInput;
  input12: typeof AntdInput;
  input13: typeof AntdInput;
  input14: typeof AntdInput;
  loginButton: typeof LoginButton;
  input: typeof AntdInput;
  embedHtml: typeof Embed;
  footerSection: typeof FooterSection;
  metaPixel: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCLandingPageContact__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCLandingPageContact__VariantsArgs;
    args?: PlasmicCLandingPageContact__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCLandingPageContact__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCLandingPageContact__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCLandingPageContact__ArgProps,
          internalVariantPropNames: PlasmicCLandingPageContact__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCLandingPageContact__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCLandingPageContact";
  } else {
    func.displayName = `PlasmicCLandingPageContact.${nodeName}`;
  }
  return func;
}

export const PlasmicCLandingPageContact = Object.assign(
  // Top-level PlasmicCLandingPageContact renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    formulario1: makeNodeComponent("formulario1"),
    img: makeNodeComponent("img"),
    h2: makeNodeComponent("h2"),
    form: makeNodeComponent("form"),
    input7: makeNodeComponent("input7"),
    input11: makeNodeComponent("input11"),
    input12: makeNodeComponent("input12"),
    input13: makeNodeComponent("input13"),
    input14: makeNodeComponent("input14"),
    loginButton: makeNodeComponent("loginButton"),
    input: makeNodeComponent("input"),
    embedHtml: makeNodeComponent("embedHtml"),
    footerSection: makeNodeComponent("footerSection"),
    metaPixel: makeNodeComponent("metaPixel"),

    // Metadata about props expected for PlasmicCLandingPageContact
    internalVariantProps: PlasmicCLandingPageContact__VariantProps,
    internalArgProps: PlasmicCLandingPageContact__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCLandingPageContact;
/* prettier-ignore-end */
