// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/ez_marketing_platform/PlasmicGlobalContextsProvider";

import { PlasmicAEditProfile } from "../components/plasmic/ez_marketing_platform/PlasmicAEditProfile";
import { useRouter } from "next/router";

import { getSupabaseA } from "../lib/a-supabaseClient";

function AEditProfile() {
  const router = useRouter();

  // ✅ SALVA TOKEN DA AGENCY SOMENTE SE AINDA NÃO EXISTIR
  React.useEffect(() => {
    const supabase = getSupabaseA();

    supabase.auth.getSession().then(({ data }) => {
      const token = data.session?.access_token;

      if (!token) return;

      if (!localStorage.getItem("sb-agency-access-token")) {
        localStorage.setItem("sb-agency-access-token", token);
      }
    });
  }, []);

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={router?.pathname}
        params={router?.query}
        query={router?.query}
      >
        <PlasmicAEditProfile />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default AEditProfile;
