import React, { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import classNames from "classnames";

// Plasmic visual primitives (permitidos)
import { PlasmicImg, PlasmicLink } from "@plasmicapp/react-web";

// IMPORTS TÓXICOS (intencionalmente reabilitados para teste)
// -> esses imports normalmente vivem no runtime/host do Plasmic ou em pacotes skinny do AntD.
import {
  // funções do host/runtime do Plasmic
  initializeCodeComponentStates,
  generateOnMutateForSpec,
} from "@plasmicapp/react-web/lib/host";

// AntD-skinny / Form internals que frequentemente causam o erro lendário
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";

// Our wrapped Plasmic components (visual)
import LoginButton from "../components/LoginButton";
import SignInWithGoogle from "../components/SignInWithGoogle";

// CSS modules generated by Plasmic
import projectcss from "../components/plasmic/ez_marketing_platform/plasmic.module.css";
import styles from "../components/plasmic/ez_marketing_platform/PlasmicLCLogin.module.css";

/**
 * ⚠️ PERIGO: Arquivo de TESTE para reproduzir o erro lendário
 * - Use apenas em branch de teste
 * - Tenha um backup/rollback pronto
 * - Não deixar em produção
 */

export default function CLoginToxic(): JSX.Element {
  // tentativa de simular o estado/plasmic internal object
  // (no código real do Plasmic isso vem via useDollarState / runtime; aqui fingimos um objeto)
  const fakePlasmicState: any = { "email.value": "", "password.value": "" };

  // 1) initializeCodeComponentStates — geralmente espera o "$state" do Plasmic.
  //    Estamos chamando aqui pro runtime tentar inicializar o código gerado pelo Plasmic.
  useEffect(() => {
    try {
      // Parâmetros simples para forçar a execução do helper
      // (na geração real o Plasmic passa specs bem maiores)
      initializeCodeComponentStates?.(
        fakePlasmicState,
        [{ name: "value", plasmicStateName: "email.value" }],
        [],
        {},
        {}
      );
    } catch (err) {
      // swallow - queremos ver o erro no console do browser (runtime)
      // mas não evitar que o resto seja executado (para reproduzir a falha lendária).
      // eslint-disable-next-line no-console
      console.log("initializeCodeComponentStates failed (expected in Codegen test):", err);
    }
  }, []);

  // 2) generateOnMutateForSpec / generateOnMutateForSpec-like call
  //    Construímos um mutationSpec simplificado e chamamos o gerador para forçar chamadas internas.
  useEffect(() => {
    try {
      const simpleMutateSpec = {
        // estrutura intencionalmente simples — apenas para acionar o caminho
        mutate: [
          {
            target: "email.value",
            op: "set",
            value: "{{event.target.value}}",
          },
        ],
      };
      // Nota: o nome exato pode variar nas versões; usamos o helper que costumava existir.
      generateOnMutateForSpec?.(simpleMutateSpec as any);
    } catch (err) {
      // eslint-disable-next-line no-console
      console.log("generateOnMutateForSpec failed (expected in Codegen test):", err);
    }
  }, []);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    console.log("TOXIC test submit", {
      email: fd.get("email"),
      password: fd.get("password"),
    });
    alert("TOXIC test submit — veja console para detalhes (design-only).");
  }

  const rootClass = classNames(
    projectcss?.plasmic_page_wrapper,
    styles.root
  );

  return (
    <>
      <Head>
        <title>Login — Ez Marketing (TOXIC TEST)</title>
        <meta name="robots" content="noindex" />
      </Head>

      <div className={rootClass} style={{ minHeight: "100vh" }}>
        <PlasmicImg
          className={styles.img}
          src={{
            src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
            fullWidth: 297,
            fullHeight: 210,
          } as any}
          alt="Ez Marketing Logo"
        />

        {/* Card */}
        <div className={classNames(projectcss?.all, styles.rectangle)}>
          <div className={classNames(projectcss?.__wab_text, styles.text__o0KFf)}>
            <h6 className={classNames(projectcss?.h6, styles.h6)}>Login (TOXIC)</h6>
          </div>

          {/* ----- AQUI: reintroduzimos o FormWrapper + FormItemWrapper + Antd inputs ----- */}
          <FormWrapper className={styles.form} onSubmit={handleSubmit}>
            <FormItemWrapper label="Email" className={styles.formField__nVf3S}>
              {/* AntdInput é parte do skinny package que costuma provocar o erro */}
              <AntdInput
                // NOTE: as props exatas esperadas pelo AntdInput/plasmic wrapper variam;
                // passamos atributos básicos para acionar a renderização do componente gerado.
                name="email"
                value={(fakePlasmicState && fakePlasmicState["email.value"]) || ""}
                onChange={(ev: any) => {
