import React from "react";
import Head from "next/head";
import Link from "next/link";
import classNames from "classnames";

// Plasmic runtime visual primitives (permitidos)
import { PlasmicImg, PlasmicLink } from "@plasmicapp/react-web";

// Our wrapped Plasmic components (visual)
import LoginButton from "../components/LoginButton";
import SignInWithGoogle from "../components/SignInWithGoogle";

// CSS modules generated by Plasmic
import projectcss from "../components/plasmic/ez_marketing_platform/plasmic.module.css";
import styles from "../components/plasmic/ez_marketing_platform/PlasmicLCLogin.module.css";

/**
 * High-risk features we KEEP DISABLED:
 * - useDollarState and family (Plasmic runtime state)
 * - generateStateOnChangeProp / generateOnMutateForSpec
 * - FormWrapper / FormItemWrapper (Plasmic form runtime)
 * - initializeCodeComponentStates
 *
 * We're enabling visual primitives only (PlasmicImg, PlasmicLink, LoginButton...)
 */

export default function CLogin(): JSX.Element {
  // Try to obtain global variant tokens/classes if available (safe fallbacks)
  const styleTokensClassNames = (() => {
    try {
      // dynamic require to avoid hard build-time dependency problems
      // module path: components/plasmic/ez_marketing_platform/plasmic.js (or .ts)
      // That module exports `_useStyleTokens` or `_useGlobalVariants` in some projects.
      // We prefer style tokens only (class names).
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const plasmicModule = require("../components/plasmic/ez_marketing_platform/PlasmicStyleTokensProvider");
      if (plasmicModule && typeof plasmicModule._useStyleTokens === "function") {
        try {
          return plasmicModule._useStyleTokens() || "";
        } catch {
          return "";
        }
      }
    } catch {
      // ignore if module not present
    }
    return "";
  })();

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    // design-only submit
    console.log("Design-only submit", {
      email: fd.get("email"),
      password: fd.get("password"),
    });
    alert("Design-only submit — values in console.");
  }

  const rootClass = classNames(
    projectcss?.plasmic_page_wrapper,
    styles.root,
    styleTokensClassNames
  );

  return (
    <>
      <Head>
        <title>Login — Ez Marketing</title>
        <meta name="robots" content="noindex" />
      </Head>

      <div className={rootClass} style={{ minHeight: "100vh" }}>
        {/* PLASMIC IMG (visual fidelity) */}
        <PlasmicImg
          className={styles.img}
          // We pass src through the "src" prop if PlasmicImg supports it; fallback to <img> if not.
          src={{
            src: "/plasmic/ez_marketing_platform/images/logo2Svg.svg",
            fullWidth: 297,
            fullHeight: 210,
          } as any}
          alt="Ez Marketing Logo"
        />

        {/* Card */}
        <div className={classNames(projectcss?.all, styles.rectangle)}>
          {/* Title */}
          <div className={classNames(projectcss?.__wab_text, styles.text__o0KFf)}>
            <h6 className={classNames(projectcss?.h6, styles.h6)}>Login</h6>
          </div>

          {/* FORM - simple, no Plasmic runtime */}
          <form className={styles.form} onSubmit={handleSubmit} noValidate>
            {/* Email */}
            <div className={styles.formField__nVf3S}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                {/* Prefer Plasmic icon as component if exists; fallback to img */}
                {/** If you have a Plasmic icon component, you can replace <img> with it. */}
                <img
                  src="/plasmic/ez_marketing_platform/icons/user.svg"
                  alt=""
                  className={styles.svg__wXpbV}
                />
                <input
                  name="email"
                  type="email"
                  placeholder="Email"
                  className={styles.email}
                  style={{
                    width: "100%",
                    padding: 10,
                    borderRadius: 8,
                    border: "1px solid #ccc",
                    fontSize: 15,
                  }}
                  autoComplete="email"
                />
              </div>
            </div>

            {/* Password */}
            <div className={styles.formField__p0HYe} style={{ marginTop: 12 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <img
                  src="/plasmic/ez_marketing_platform/icons/lock.svg"
                  alt=""
                  className={styles.svg__ihNhg}
                />
                <input
                  name="password"
                  type="password"
                  placeholder="Password"
                  className={styles.password}
                  style={{
                    width: "100%",
                    padding: 10,
                    borderRadius: 8,
                    border: "1px solid #ccc",
                    fontSize: 15,
                  }}
                  autoComplete="current-password"
                />
              </div>
            </div>

            {/* Login button: use Plasmic-wrapped visual LoginButton component (no form runtime) */}
            <div style={{ display: "flex", justifyContent: "center", marginTop: 16 }}>
              {/* The LoginButton component we have is a visual wrapper. It may expect props; we use it as visual only. */}
              <LoginButton
                // @ts-ignore (plasmic wrapper props may vary)
                className={styles.loginButton}
                style={{ width: 248, height: 37, borderRadius: 8 }}
              >
                <div style={{ color: "#fff", fontWeight: 600 }}>Login</div>
              </LoginButton>
            </div>

            {/* Forgot password -> use PlasmicLink for better visuals */}
            <div style={{ width: "100%", paddingLeft: 6, marginTop: 10 }}>
              <PlasmicLink component={Link} href="/c-reset-password" className={styles.link__o7Usc}>
                Forgot password?
              </PlasmicLink>
            </div>

            {/* Google sign-in visual button */}
            <div style={{ display: "flex", justifyContent: "center", marginTop: 12 }}>
              <SignInWithGoogle
                // visual component, hooked to no runtime
                className={styles.signInWithGoogle}
                // Provide fallback click so user sees something
                onClick={() => alert("Google sign-in disabled in design-only mode")}
              />
            </div>
          </form>

          {/* Create account */}
          <div className={styles.createAccount} style={{ marginTop: 18 }}>
            <div className={styles.text__aXkee}>New to Ez Marketing?</div>
            <PlasmicLink component={Link} href="/c-create-account" className={styles.link__dNNeM}>
              Create account
            </PlasmicLink>
          </div>
        </div>
      </div>
    </>
  );
}
